### ISSUE TITLE
author-year格式下，参考文献列表加序号

### ISSUE THREAD

**Issue by Chanmansyun** [zepinglee/gbt7714-bibtex-style#100]
你好，非常感谢您提供的模板方便了我毕业论文的撰写。在老师审阅的过程中，希望我能在参考文献列表的参考文献前像numerical格式一样，加上”[1]“这样的编号，我看了自定义样式处没有这个选项，但是转numerical的话，文内要重新修改。所以想来请问，如何在author-year格式下，给参考文献列表添加序号呢？感谢！

**Comment by sikouhjw** [comment]
建议使用 biblatex。
```tex
\documentclass{ctexart}
\usepackage[backend=biber,bibstyle=gb7714-2015,citestyle=gb7714-2015ay]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
  \cite{westfahl:space}
  \nocite{*}
  \printbibliography
\end{document}
```

**Comment by zepinglee** [comment]
> 你好，非常感谢您提供的模板方便了我毕业论文的撰写。在老师审阅的过程中，希望我能在参考文献列表的参考文献前像numerical格式一样，加上”[1]“这样的编号，我看了自定义样式处没有这个选项，但是转numerical的话，文内要重新修改。所以想来请问，如何在author-year格式下，给参考文献列表添加序号呢？感谢！

在 `\bibliography` 前添加 `\citestyle{super}`。另外建议向老师解释清楚国标的要求“著者-出版年制”参考文献表不带序号。

<img width="714" alt="Screen Shot 2022-04-23 at 12 30 58" src="https://user-images.githubusercontent.com/12290822/164877274-c9337f24-d392-4772-a3a5-1976d5f1a517.png">

**Comment by zepinglee** [comment]
> 建议使用 biblatex。
> 
> ```
> \documentclass{ctexart}
> \usepackage[backend=biber,bibstyle=gb7714-2015,citestyle=gb7714-2015ay]{biblatex}
> \addbibresource{biblatex-examples.bib}
> \begin{document}
>   \cite{westfahl:space}
>   \nocite{*}
>   \printbibliography
> \end{document}
> ```

直接使用 `bibstyle=gb7714-2015` 有些问题：

1. “著者-出版年”制的参考文献表中，出版年是紧跟着著者姓名的。这样同引用中的格式相近，方便读者寻找。而顺序编码制的出版年在出版社后。
2. 两者的排序的排序方式不同。

**Comment by Chanmansyun** [comment]
非常谢谢两位的回复！（其实我在答辩现场就这样回复答辩老师的，GB/T 7714-2015是不用带编号的。无奈，你懂的😂
