### ISSUE TITLE
如何控制参考文献英文在前，中文在后？

### ISSUE THREAD

**Issue by alone-tree** [zepinglee/gbt7714-bibtex-style#102]
我在使用时发现参考文献列表默认中文文献在前，英文在后，想要调整这一排列顺序，请问是否支持该功能？

**Comment by zepinglee** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/blob/f7e42092047bebfdec0d2dedf46b61eab2195fb1/gbt7714-author-year.bst#L98-L102

这里设置了各个语言的顺序，可以修改对应的数值。

**Comment by alone-tree** [comment]
亲测好用，非常感谢！
