### ISSUE TITLE
如何让volume的结果显示在年份之后并显示number

### ISSUE THREAD

**Issue by HoeYeungHo** [zepinglee/gbt7714-bibtex-style#103]
## 编译环境
宏包版本：gbt7714 v2.0

## 描述问题
在Google学术中，会议录（inproceedings）的卷号（volume）是显示在年份之后，编号（number）是显示在卷号之后的。而使用默认设置下，卷号是显示在会议录标题（booktitle）之后的。请问如何调整为Google学术中的样式，谢谢。

bib 数据库代码：
```TeX
@inproceedings{hu2019scale,
  title={A scale transform and deformation target tracking algorithm based on correlation filtering},
  author={Hu, Cong and Xia, Wei and Chen, Peng and Huang, Shun and Guo, Hui and Jin, Xing},
  booktitle={IOP Conference Series: Materials Science and Engineering},
  volume={569},
  number={5},
  pages={052051},
  year={2019},
  organization={IOP Publishing}
}
```

截图：
**Google学术中的结果：**
Hu C, Xia W, Chen P, et al. A scale transform and deformation target tracking algorithm based on correlation filtering[C]//IOP Conference Series: Materials Science and Engineering. IOP Publishing, 2019, 569(5): 052051.
**我编译的结果：**
Hu C, Xia W, Chen P, et al. A Scale Transform and Deformation Target Tracking Algorithm Based on Correlation Filtering[C]//IOP Conference Series: Materials Science and Engineering: volume 569. IOP Publishing, 2019: 052051

**Comment by sikouhjw** [comment]
![图片](https://user-images.githubusercontent.com/49770925/166438385-9d0410b9-0a87-4889-a366-b927b701a60a.png)

请你先弄清楚，Google 学术导出的结果不代表是正确的。

`texdoc gbt7714` 是根据国标来定制的宏包，如果有私人化定制需求，建议自行学习 bst 文件的修改。

我对 bst 不熟，你需要修改的应该是这部分
https://github.com/zepinglee/gbt7714-bibtex-style/blob/f7e42092047bebfdec0d2dedf46b61eab2195fb1/gbt7714-numerical.bst#L1748-L1750

**Comment by zepinglee** [comment]
@HoeYeungHo 这个“2019, 569(5)”的格式是期刊的“年, 卷(期)”

国标 4.2 节 专著中的析出文献
<img width="714" alt="Screen Shot 2022-05-03 at 19 48 49" src="https://user-images.githubusercontent.com/12290822/166447489-c18e49d2-c74b-413c-8f1c-27f6ce626275.png">

4.4 节 连续出版物中的析出文献
<img width="713" alt="Screen Shot 2022-05-03 at 19 49 11" src="https://user-images.githubusercontent.com/12290822/166447560-841df65b-23f4-49cb-8ad4-0ecdfe49d3dd.png">

所以关键在于“IOP Conference Series: Materials Science and Engineering”是“专著”（包括会议论文集）还是“连续出版物”。虽然 Google 学术的文献类型是 `@inproceedings`，文章官网 <https://doi.org/10.1088/1757-899x/569/5/052051> 导出的 BibTeX 数据库却是 `@article`。我个人认为既然有卷号和期号的情况下，应该用期刊文献 `@article` 更合适。
