### ISSUE TITLE
会议论文卷号显示问题

### ISSUE THREAD

**Issue by gongliangjun** [zepinglee/gbt7714-bibtex-style#104]
## 编译环境
宏包版本：gbt7714 v2
标注样式：numbers 

## 描述问题
请问引用的会议论文的卷号显示结果是否是规范的，如果不规范怎么修改能达到和官网一致的效果

bib 数据库代码：
```TeX
@inproceedings{zhao2021effects,
	author = {Lei Zhao and Chuanlu Zang and YongAo He and YiXian Yang},
	title = {{Effects of different test media on the test results of automobile cabin air filter}},
	volume = {12058},
	booktitle = {Fifth International Conference on Traffic Engineering and Transportation System (ICTETS 2021)},
	publisher = {SPIE},
	pages = {650 -- 656}, 
	year = {2021},
}
```

编译结果：

![](https://raw.githubusercontent.com/gongliangjun/blog-images/master/202205052003732.png)

此会议论文出版社官网引用格式：

![](https://raw.githubusercontent.com/gongliangjun/blog-images/master/202205052005488.png)

[会议论文网址](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12058/120582O/Effects-of-different-test-media-on-the-test-results-of/10.1117/12.2619723.short?SSO=1)

**Comment by zepinglee** [comment]
GB/T 7714 的会议论文属于“专著的析出文献”，卷号通常作为专著的“其他提名信息”，比如示例 [4] 和 [5]，所以显示结果是规范的。官网的格式并非 GB/T 7714，不能直接比较。
<img width="724" alt="Screen Shot 2022-05-05 at 20 19 09" src="https://user-images.githubusercontent.com/12290822/166921657-7c9f5834-4874-43c6-a7ab-1a92c5812aa8.png">

可能“volume” 这个词改为“Vol.”更合适些，因为英文的冒号后通常使用大写，而且 GB/T 7714 的“edition”使用了缩写“ed.”，这样更一致。

**Comment by gongliangjun** [comment]
请问如何能修改能显示成“Vol.”

**Comment by gongliangjun** [comment]
请问如何修改才能显示“Vol.”呢

**Comment by zepinglee** [comment]
> 请问如何修改才能显示“Vol.”呢

参考 fb0bf54。

**Comment by gongliangjun** [comment]
谢谢！

**Comment by zhuoju36** [comment]
> ## 编译环境
> 宏包版本：gbt7714 v2 标注样式：numbers
> 
> ## 描述问题
> 请问引用的会议论文的卷号显示结果是否是规范的，如果不规范怎么修改能达到和官网一致的效果
> 
> bib 数据库代码：
> 
> ```
> @inproceedings{zhao2021effects,
> 	author = {Lei Zhao and Chuanlu Zang and YongAo He and YiXian Yang},
> 	title = {{Effects of different test media on the test results of automobile cabin air filter}},
> 	volume = {12058},
> 	booktitle = {Fifth International Conference on Traffic Engineering and Transportation System (ICTETS 2021)},
> 	publisher = {SPIE},
> 	pages = {650 -- 656}, 
> 	year = {2021},
> }
> ```
> 
> 编译结果：
> 
> ![](https://raw.githubusercontent.com/gongliangjun/blog-images/master/202205052003732.png)
> 
> 此会议论文出版社官网引用格式：
> 
> ![](https://raw.githubusercontent.com/gongliangjun/blog-images/master/202205052005488.png)
> 
> [会议论文网址](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12058/120582O/Effects-of-different-test-media-on-the-test-results-of/10.1117/12.2619723.short?SSO=1)

倒是好奇[C]后面为什么会有两个斜杠//

**Comment by zepinglee** [comment]
> 倒是好奇[C]后面为什么会有两个斜杠//

[国标](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf) 要求。
<img width="708" alt="Screen Shot 2022-06-15 at 18 58 15" src="https://user-images.githubusercontent.com/12290822/173811491-4a2ef70e-cae0-4c55-ae0a-9106f5702650.png">
