### ISSUE TITLE
学位论文出版地

### ISSUE THREAD

**Issue by yangtzech** [zepinglee/gbt7714-bibtex-style#106]
部分学校校区分布在多个城市，学位论文出版地应该是校区所在地还是学校注册地？

**Comment by zepinglee** [comment]
按照《[关于执行 GB/T 7714 若干问题的释疑](https://www.opticsjournal.net/upload/post/201604/PT160414000034Zw3y.pdf)》，应该是填学位的“授予地”，应该是校区所在地。

**Comment by yangtzech** [comment]
感谢！
