### ISSUE TITLE
为何加到项目里不生效呢，求助

### ISSUE THREAD

**Issue by yangyuke001** [zepinglee/gbt7714-bibtex-style#112]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
我想把引用中的作者全部是大写改成只是首字母大写，然后将2个关键的文件加入我项目里，按照参考
将如下代码改成：

#0 'uppercase.name :=

以及也参考了作者的其他写法，都不生效，猜测是gbt7714在我项目里没法用吗？

截图1：
![Screenshot_3](https://user-images.githubusercontent.com/27425366/204026990-e9454338-eaa9-4b5d-9b56-5865cbfe134b.png)

截图1：
![Screenshot_4](https://user-images.githubusercontent.com/27425366/204027010-90b11778-5623-4002-b229-bc85a106cfea.png)

**Comment by zepinglee** [comment]
主文件是哪个？其中调用的是 `gbt7714-2005-plain.bst` 吗？

**Comment by yangyuke001** [comment]
> 主文件是哪个？其中调用的是 `gbt7714-2005-plain.bst` 吗？

感谢作者回复！
我是参考这个：https://blog.csdn.net/qq_39463175/article/details/123538179?spm=1001.2101.3001.6650.4&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-4-123538179-blog-104867559.pc_relevant_recovery_v2&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-4-123538179-blog-104867559.pc_relevant_recovery_v2&utm_relevant_index=5

将gbt7714.sty和gbt7714-2005-plain.bst放到了我项目里，并改成了0，看作者名字还没有变成我想要的。

因为我对overleaf这些不是很熟，感觉是没有调用gbt7714-2005-plain.bst成功，
麻烦作者了，再次感谢！

**Comment by yangyuke001** [comment]
对不起，应该我项目里的有个地方影响了，现在解决了：

packages 里有个地方：

gbnamefmt=lowercase,

解注释就行了。

**Comment by zepinglee** [comment]
gbnamefmt 是 biblatex-gb7714 的选项，与本项目无关。

**Comment by RainyWantsToBeSunny** [comment]
是调用包的时候参数问题。参考我写的csdn博客：
[有效]在overleaf中GB/T 7714把作者名字全大写改成小写：[](https://blog.csdn.net/weixin_51429895/article/details/129308777)

**Comment by sikouhjw** [comment]
> 是调用包的时候参数问题。参考我写的csdn博客： [有效]在overleaf中GB/T 7714把作者名字全大写改成小写：(https://blog.csdn.net/weixin_51429895/article/details/129308777)

這裏不是給你打廣告的地方

**Comment by zepinglee** [comment]
> 是调用包的时候参数问题。参考我写的csdn博客： [有效]在overleaf中GB/T 7714把作者名字全大写改成小写：(https://blog.csdn.net/weixin_51429895/article/details/129308777)

你讨论的是 <https://github.com/hushidong/biblatex-gb7714-2015> 跟本项目无关。另外我搞不懂这种描述一个参数的文章有什么价值。

**Comment by RainyWantsToBeSunny** [comment]
> > 是调用包的时候参数问题。参考我写的csdn博客： [有效]在overleaf中GB/T 7714把作者名字全大写改成小写：(https://blog.csdn.net/weixin_51429895/article/details/129308777)
> 
> 你讨论的是 https://github.com/hushidong/biblatex-gb7714-2015 跟本项目无关。另外我搞不懂这种描述一个参数的文章有什么价值。

首先说声抱歉，我今天找了一天怎么在overleaf里正确引用这个bibtex的gbt7714包——我和这个issue提出者遇到了一样的问题，并且也像ta一样看了好几个blog都没有解决，所以干脆自己写了一个blog回答。然后在我认为相关的、并且被我反复搜到的issue下面留了传送门。如果实际上我发到了错误的地方，那么我道歉，我自己会删除。

但是我不认同您“描述一个参数的文章有什么价值”这样的话。能解决问题就是价值，在您看来可能就是一个参数的事情，对于不了解这个项目的人来说却会非常苦手。我本意只是希望像我一样的人少走一些弯路而已。

**Comment by zepinglee** [comment]
> 首先说声抱歉，我今天找了一天怎么在overleaf里正确引用这个bibtex的gbt7714包——我和这个issue提出者遇到了一样的问题，并且也像ta一样看了好几个blog都没有解决，所以干脆自己写了一个blog回答。然后在我认为相关的、并且被我反复搜到的issue下面留了传送门。如果实际上我发到了错误的地方，那么我道歉，我自己会删除。
> 
> 但是我不认同您“描述一个参数的文章有什么价值”这样的话。能解决问题就是价值，在您看来可能就是一个参数的事情，对于不了解这个项目的人来说却会非常苦手。我本意只是希望像我一样的人少走一些弯路而已。

有问题的话读宏包文档 <http://mirrors.ctan.org/biblio/bibtex/contrib/gbt7714/gbt7714.pdf> <http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf>。
