### ISSUE TITLE
请问如何消除这个warning，以前的版本没有这个warning

### ISSUE THREAD

**Issue by DangeRS2** [zepinglee/gbt7714-bibtex-style#113]
## 编译环境
宏包版本：gbt7714 v2.1.4 （overleaf TeXLive2022）
标注样式：super or numbers

## 描述问题
新版本编译总是有`isn't a brace-balanced string for entry`相关的warning，虽然最后的内容似乎没什么问题，但是看着非常糟心。请问能通过修改bst的某些地方消除这个warning吗？

老版本MWE（v1.1.1）：
```LaTeX
\documentclass{article}

\usepackage[numbers]{gbt7714}

\begin{filecontents}{Ref.bib}
@article{Bjornson2019,
  author        = "Bjornson, Emil and Van der Perre, Liesbet and Buzzi, Stefano and Larsson, Erik G.",
  title         = "Massive {MIMO} in Sub-6 {GHz} and {mmWave}: {Physical}, Practical, and Use-Case Differences",
  journal       = IEEE_M_WC,
  volume        = "26",
  number        = "2",
  pages         = "100-108",
  month         = apr,
  year          = "2019"
}
\end{filecontents}

\begin{document}

\cite{Bjornson2019}

\bibliography{IEEEfull,Ref}

\end{document}
```

新版本MWE：
```LaTeX
\documentclass{article}

\usepackage{gbt7714}
\citestyle{numbers}

% \bibliographystyle{IEEEtran}
\bibliographystyle{gbt7714-numerical}


\begin{filecontents}{Ref.bib}
@article{Bjornson2019,
  author        = "Bjornson, Emil and Van der Perre, Liesbet and Buzzi, Stefano and Larsson, Erik G.",
  title         = "Massive {MIMO} in Sub-6 {GHz} and {mmWave}: {Physical}, Practical, and Use-Case Differences",
  journal       = IEEE_M_WC,
  volume        = "26",
  number        = "2",
  pages         = "100-108",
  month         = apr,
  year          = "2019"
}
\end{filecontents}

\begin{document}

\cite{Bjornson2019}

\bibliography{IEEEfull,Ref}

\end{document}
```

或者可以直接浏览overleaf项目：https://cn.overleaf.com/read/wqwsycrgtdhg

另外附上`IEEEfull.bib`的内容：https://mirror.math.princeton.edu/pub/CTAN/macros/latex/contrib/IEEEtran/bibtex/IEEEfull.bib

## 截图：
老版本日志：
![Snipaste_2023-01-23_11-59-28](https://user-images.githubusercontent.com/49086184/214103182-d2ee50ad-0558-4bb7-8c6f-0edc95022f88.png)

新版本日志：
![Snipaste_2023-01-23_11-59-13](https://user-images.githubusercontent.com/49086184/214103190-12b9426e-e646-4fd5-8753-8def7f6cf430.png)

**Comment by zepinglee** [comment]
我能复现这个问题，是下面这行导致的。

https://github.com/zepinglee/gbt7714-bibtex-style/blob/7ab18f49f77a34a9f993160b4273dfff6c22f149/gbt7714.dtx#L2607

这里是为了判断 `journal` 字段是否是 `arXiv: ...`，但是在你的案例中，`#1 #5 substring$` 会得到 `"{IEEE"`，在 `"l" change.case$` 时就会报 warning。

添加一步 `purify$` 应该可以解决。

**Comment by zepinglee** [comment]
Overleaf 不太可能更新，建议将修改后的 <https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-numerical.bst> 传到项目中。

**Comment by DangeRS2** [comment]
感谢及时回复~
