### ISSUE TITLE
你好，请问如何将会议名称后面的句点改为逗号呢？

### ISSUE THREAD

**Issue by Echoleung** [zepinglee/gbt7714-bibtex-style#115]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：numbers

## 描述问题
我们学校给出的会议参考样式如图所示，要求会议名称后面为","

<img width="930" alt="image" src="https://user-images.githubusercontent.com/23042248/221786489-b8d6003d-1f8c-4667-8d2d-1c5eeb413eec.png">

而我现在得到的参考文献样式会议名称后面是"."，请问如何修改呢？
这是我现在的样式：
<img width="592" alt="image" src="https://user-images.githubusercontent.com/23042248/221786528-f3f18c40-7279-4399-8497-3bee0f68ab56.png">

bib 数据库代码：
```TeX
@inproceedings{bergamasco2015adopting,
  title={Adopting an unconstrained ray model in light-field cameras for 3d shape reconstruction},
  author={Bergamasco, Filippo and Albarelli, Andrea and Cosmo, Luca and Torsello, Andrea and Rodola, Emanuele and Cremers, Daniel},
  booktitle={Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition},
  pages={3003--3012},
  address={Boston, USA},
  year={2015}
}
```

截图：

**Comment by Echoleung** [comment]
宏包版本应该是2.0，忘记修改了

**Comment by zepinglee** [comment]
`address` 是出版地不是会议地。目前可行的办法是将 `Boston, USA` 填在 `booktitle`。

```bibtex
  booktitle={Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition, Boston, USA},
```

严格地讲，`booktitle` 是论文集的标题不是会议名，`year` 是出版年不是会议年。`biblatex` 有一套 `eventtitle`, `eventdate`, `venue` 字段分别对应会议名、会议年、会议地，但目前本样式中并没有使用，需要一定的开发时间。

**Comment by Echoleung** [comment]
> `address` 是出版地不是会议地。目前可行的办法是将 `Boston, USA` 填在 `booktitle`。
> 
> ```
>   booktitle={Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition, Boston, USA},
> ```
> 
> 严格地讲，`booktitle` 是论文集的标题不是会议名，`year` 是出版年不是会议年。`biblatex` 有一套 `eventtitle`, `eventdate`, `venue` 字段分别对应会议名、会议年、会议地，但目前本样式中并没有使用，需要一定的开发时间。

感谢您的热心回复，尝试将地址信息改到了`booktitle`，可是由于`booktitle`后面接的是`.`，导致`year`信息前显示的是`.`。但是鉴于您这个思路，我将`year`和`pages`信息都放入了`booktitle`中，现在可以达到学校要求的效果。

**Comment by zepinglee** [comment]
> 感谢您的热心回复，尝试将地址信息改到了`booktitle`，可是由于`booktitle`后面接的是`.`，导致`year`信息前显示的是`.`。

我还是再改一下 bst 吧，你们学校的 latex 模板是哪个？

> 但是鉴于您这个思路，我将`year`和`pages`信息都放入了`booktitle`中，现在可以达到学校要求的效果。

感觉这样有些太不方便了。

**Comment by zepinglee** [comment]
> 您好，我已通过邮件将模版发送给您，麻烦您了。 邮件主题：latex模版(FROM Echoleung)

我好像没收到。有没有 GitHub 链接？

**Comment by Echoleung** [comment]
> 

您好，我已上传到我的github：https://github.com/Echoleung/latex_template

**Comment by Echoleung** [comment]
> > 您好，我已通过邮件将模版发送给您，麻烦您了。 邮件主题：latex 模版 (FROM Echoleung)
> 
> 我好像没收到。有没有 GitHub 链接？


您好，我已上传到我的 github：https://github.com/Echoleung/latex_template

**Comment by zepinglee** [comment]
我周末的时候改一下 .bst 吧。

> 您好，我已上传到我的 github：https://github.com/Echoleung/latex_template

这个模板是来自哪里？我还搜到了 <https://github.com/lusccc/cqupt-thesis>，跟这个模板有没有联系？

**Comment by zepinglee** [comment]
@Echoleung <https://github.com/Echoleung/latex_template> 这个模板是在 GitHub 上维护的吗？

**Comment by sikouhjw** [comment]
> @Echoleung https://github.com/Echoleung/latex_template 这个模板是在 GitHub 上维护的吗？

我估计不是，应该是类似祖传性质的模板

**Comment by Echoleung** [comment]
> 我周末的时候改一下 .bst 吧。
> 
> > 您好，我已上传到我的 github：https://github.com/Echoleung/latex_template
> 
> 这个模板是来自哪里？我还搜到了 https://github.com/lusccc/cqupt-thesis，跟这个模板有没有联系？

跟这个模版没关系，我们现在用的是学校新发布的，但是只在学校官网上进行更新，没有官方的GitHub。

**Comment by zepinglee** [comment]
> 跟这个模版没关系，我们现在用的是学校新发布的，但是只在学校官网上进行更新，没有官方的GitHub。

最好跟这个模板的作者联系一下，将模板放在 github 上，这样方便记录更新以及反馈 bug。

**Comment by zepinglee** [comment]
我在 [`cqupt`](https://github.com/zepinglee/gbt7714-bibtex-style/tree/cqupt) 分支中将会议论文的格式改为“会议名, 会议地, 会议年”，修改后的版本：[gbt7714-2005-numerical.bst](https://github.com/zepinglee/gbt7714-bibtex-style/blob/cqupt/gbt7714-2005-numerical.bst)，

测试效果见 <https://github.com/zepinglee/gbt7714-bibtex-style/blob/f157e95463f346e7a0c1d0ba6aa06f066f4d1c36/test/testbst/2015-numerical.bbl#L150-L154> 和 <https://github.com/zepinglee/gbt7714-bibtex-style/blob/f157e95463f346e7a0c1d0ba6aa06f066f4d1c36/test/testbst/2015-numerical.bbl#L722-L727>。

**Comment by zepinglee** [comment]
> 大佬您好，我也是CQUPT的，但是不懂代码，请问您那边调好了吗，能不能发一个CSL文件呀？万分感谢！

@AlanChen66 CSL 样式见 <https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl/issues/I6JUGM#note_16688172_link>。不过在 LaTeX 中使用 CSL 样式需要使用 <https://github.com/zepinglee/citeproc-lua>，但是目前还没有支持双语言，估计需要一段时间才能完成。
