### ISSUE TITLE
参考文献引入为问号

### ISSUE THREAD

**Issue by earlyEpiphyte** [zepinglee/gbt7714-bibtex-style#116]
我将压缩包直接导入overleaf，然后随便测试了一个参考文献，编译出来是问号，请问是咋回事呢

**Comment by zepinglee** [comment]
给个 [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)？

**Comment by zepinglee** [comment]
一般要将 `.bst` 跟 `.tex` 文件放在一起。

TeX Live 选择的是哪个版本？把报错信息也贴一下？

**Comment by earlyEpiphyte** [comment]
TeX Live 为2022，没有错误，只有warning。
```
Package natbib Warning: Citation `b2' on page 1 undefined on input line 10.
Package natbib Warning: There were undefined citations.
```

**Comment by earlyEpiphyte** [comment]
可以了，之前`.bst`文件里面的是别的文件的引用，我把它替换成引用的文件就行了，十分感谢
