### ISSUE TITLE
修改了gbt7714-numerical.bst文件中的"in" 'component.part.label :=，但是并不起作用

### ISSUE THREAD

**Issue by Zhen715code** [zepinglee/gbt7714-bibtex-style#117]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
我不想要会议出现双斜线，于是修改了`gbt7714-numerical.bst`文件中的`"in" 'component.part.label :=`，但是并不起作用。请求您的帮助
以下是我的一些设置：
主文件：`\usepackage{gbt7714}`
引入参考文献的文件：
```tex
\bibliographystyle{gbt7714-numerical}
\bibliography{ref}
```

bib文件
```bibtex
@inproceedings{razorenova2020deep,
	title={Deep learning for non-invasive cortical potential imaging},
	author={Razorenova, Alexandra and Yavich, Nikolay and Malovichko, Mikhail and Fedorov, Maxim and Koshev, Nikolay and Dylov, Dmitry V},
	booktitle={Machine Learning in Clinical Neuroimaging and Radiogenomics in Neuro-oncology: Third International Workshop, MLCN 2020, and Second International Workshop, RNO-AI 2020, Held in Conjunction with MICCAI 2020, Lima, Peru, October 4--8, 2020, Proceedings 3},
	pages={45--55},
	year={2020},
	organization={Springer}
}
```

截图：
![image](https://user-images.githubusercontent.com/118883154/222745644-5abb863f-a3bb-4cd6-be3c-05df83822d55.png)

**Comment by Zhen715code** [comment]
写错了，设置的是"none" 'component.part.label :=

**Comment by zepinglee** [comment]
我无法无限这个问题。

```tex
\documentclass{ctexart}

\usepackage{gbt7714}

\begin{filecontents*}[overwrite]{\jobname.bib}
@inproceedings{razorenova2020deep,
  title        = {Deep learning for non-invasive cortical potential imaging},
  author       = {Razorenova, Alexandra and Yavich, Nikolay and Malovichko, Mikhail and Fedorov, Maxim and Koshev, Nikolay and Dylov, Dmitry V},
  booktitle    = {Machine Learning in Clinical Neuroimaging and Radiogenomics in Neuro-oncology: Third International Workshop, MLCN 2020, and Second International Workshop, RNO-AI 2020, Held in Conjunction with MICCAI 2020, Lima, Peru, October 4--8, 2020, Proceedings 3},
  pages        = {45--55},
  year         = {2020},
  organization = {Springer},
}
\end{filecontents*}


\begin{document}

\nocite{*}
\bibliographystyle{gbt7714-numerical}
\bibliography{\jobname}

\end{document}
```

<img width="529" alt="Screenshot 2023-03-03 at 22 49 45" src="https://user-images.githubusercontent.com/12290822/222751062-e4c3b128-0227-40b2-9368-57a0cb2a2880.png">

**Comment by zepinglee** [comment]
可能是 `\bibliographystyle{gbt7714-numerical}` 没有找到正确的 `.bst` 文件。建议将修改后的 `.bst` 文件跟 `.tex` 文件放在一起。

**Comment by wtzuoluo** [comment]
您好！请问如何将gbt7714-numberical.bst参考文献中人名的大写修改为下图的格式？
![54ffbf6381dc5ef90087fa6c3254f09](https://user-images.githubusercontent.com/44955490/223470797-c9e163bc-0e5a-4226-8fca-c485f57edd3c.jpg)

**Comment by zepinglee** [comment]
> 您好！请问如何将gbt7714-numberical.bst参考文献中人名的大写修改为下图的格式？ ![54ffbf6381dc5ef90087fa6c3254f09](https://user-images.githubusercontent.com/44955490/223470797-c9e163bc-0e5a-4226-8fca-c485f57edd3c.jpg)

1. 在 issues 中搜索问题；2. 不要发在无关的 issue 中；3. 参考 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/78#issuecomment-810107333>。

**Comment by wtzuoluo** [comment]
十分抱歉，博主。十分感谢您的回复！
