### ISSUE TITLE
您好！请问，\biband {和} 如何设置才能工作？

### ISSUE THREAD

**Issue by OceansDeep0219** [zepinglee/gbt7714-bibtex-style#118]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式 : authoryear

## 描述问题：
在 ucasthesis (https://github.com/mohuangrui/ucasthesis) 模板第9页的例子中，在中文环境下，
若使用 \citet*{betts2005aging} 输出为 Betts and Taylor (2005) 无法将 “and” 转换成中文的”和“
若使用 \citet{betts2005aging} 输出为 Betts 等 (2005)

如何设置？ 使用 \citet{betts2005aging} 这个命令输出类似 Betts 和 Taylor (2005)这样的结果.

期待您的回复，谢谢！

\providecommand{\biband}{和}
\bibitem[Betts {\bibetal}(2005)Betts and Taylor]{betts2005aging}
Betts~L~R, Taylor~C~P.
\newblock Aging reduces center-surround antagonism in visual motion processing
  [J].
\newblock Neuron, 2005, 45\penalty0 (3): 361-366.
发现并没有使用 \biband 命令
```

截图：

**Comment by lss-len** [comment]
将 #2 'citation.et.al.min :=    修改为       
#3 'citation.et.al.min :=
