### ISSUE TITLE
会议引用title与booktitle中间的的链接为“\\”，如何修改为“.” ；参考文献大小写

### ISSUE THREAD

**Issue by a-delicious-girl** [zepinglee/gbt7714-bibtex-style#119]
## 编译环境
宏包版本：gbt7714 v2.1.5
标注样式：     \usepackage{gbt7714}
                        \bibliographystyle{gbt7714-numerical}
编译器：Texlive2022

## 描述问题
1.要求            会议题目(title)[C]. 会议名(booktitle)
   编译结果    会议题目(title)[C]//会议名(booktitle)

2. 要求   参考文献中所有实词大写，在bib文件中已经修改，编译结果只有首字母大写。

请问如何修改gbt7714-numerical.bst文件。查看gbt7714.pdf文档后，依然不会修改该gbt7714-numerical.bst

bib 数据库代码：
```TeX
@inproceedings{R19,
  title={Random K-labelsets: An Ensemble Method for Multilabel Classification},
  author={Tsoumakas, Grigorios and Vlahavas, Ioannis},
  booktitle={European Conference on Machine Learning},
  pages={406--417},
  year={2007},
  organization={Springer},
  note={doi:{\color{blue}
\href{http://dx.doi.org/10.1007/978-3-540-74958-5_38}{10.1007/978-3-540-74958-5\_38}}}
}
```

截图：
该图为编译结果
![参考文献](https://user-images.githubusercontent.com/52501516/223017588-3846a6de-12fc-4a99-af2f-ee606172d415.png)
该文档为参考文献要求：
[重庆邮电大学博士研究生学位论文模板（2022版）.pdf](https://github.com/zepinglee/gbt7714-bibtex-style/files/10894305/2022.pdf)
参考文献描述在31页至33页

**Comment by a-delicious-girl** [comment]
问题1，修改方法  将gbt7714-numerical.bst文件中的
"slash" 'component.part.label :=
修改为：
"none" 'component.part.label :=

**Comment by a-delicious-girl** [comment]
问题2，将bib文件中参考title部分用两层大括号包裹
`@inproceedings{R19,
  title={{Random K-labelsets: An Ensemble Method for Multilabel Classification}},
  author={Tsoumakas, Grigorios and Vlahavas, Ioannis},
  booktitle={European Conference on Machine Learning},
  pages={406--417},
  year={2007},
  organization={Springer},
  note={doi:{\color{blue}
\href{http://dx.doi.org/10.1007/978-3-540-74958-5_38}{10.1007/978-3-540-74958-5\_38}}}
}`

**Comment by sikouhjw** [comment]
你要是想加 doi，请使用 `doi` 而不是 `note`。

**Comment by zepinglee** [comment]
> 1.要求 会议题目(title)[C]. 会议名(booktitle) 编译结果 会议题目(title)[C]//会议名(booktitle)

CQUPT 的格式修改见 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/115#issuecomment-1458492810>。
 
> 2. 要求   参考文献中所有实词大写，在bib文件中已经修改，编译结果只有首字母大写。

`.bib` 数据库的标题应该使用 title case（参考 <https://en.wikipedia.org/wiki/Title_case>），并且将专有名词用大括号保护起来。BibTeX 可以将 title case 的标题转为 sentence case（<https://en.wikipedia.org/wiki/Letter_case#Sentence_case>），专有名词受大括号保护不会转换大小写。

CQUPT 的要求是“除特殊名词外，英文文献标题(论文题目、书名)仅第一个单词的首字母大写，其余全部小写”，即 sentence case，所以不必调整。

**Comment by zepinglee** [comment]
> 问题2，将bib文件中参考title部分用两层大括号包裹
> 
> ```
> @inproceedings{R19,
>   title={{Random K-labelsets: An Ensemble Method for Multilabel Classification}},
>   author={Tsoumakas, Grigorios and Vlahavas, Ioannis},
>   booktitle={European Conference on Machine Learning},
>   pages={406--417},
>   year={2007},
>   organization={Springer},
>   note={doi:{\color{blue}
> \href{http://dx.doi.org/10.1007/978-3-540-74958-5_38}{10.1007/978-3-540-74958-5\_38}}}
> }
> ```
> 
> 回答来自https://blog.csdn.net/jizhidexiaoming/article/details/80909619

用大括号保护专有名词，不要把整个标题括起来。后者会防止 Bib(La)TeX 样式转换大小写。参考 <https://github.com/ustctug/ustcthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E8%8B%B1%E6%96%87%E6%A0%87%E9%A2%98%E4%B8%BA%E4%BD%95%E8%A2%AB%E8%BD%AC%E4%B8%BA%E5%B0%8F%E5%86%99>。

另外 DOI 可以直接填在 `doi = {10.1007/978-3-540-74958-5_38}`，不必在 `note` 手动处理个事。
