### ISSUE TITLE
正文中引用英文文献作者时 'et al.' 改成“等”以及去掉'et al.' 前后的空格

### ISSUE THREAD

**Issue by yangtzech** [zepinglee/gbt7714-bibtex-style#120]
目前我使用的方法是：
```
\citeauthor{key}提出了一种方法 \cite{key}。
```
得到的结果是
```
A et al. 提出了一种方法[1]。
```
但我想要的效果是：
```
A等提出了一种方法[1]。
```
citeauthor正文中引用英文论文时，
1、把英文的et al.改成等
2、去掉等前后的空格

我使用的模板是https://github.com/1FCENdoge/SYSUThesis ，尝试了使用`\newcommand\bibetal{等}
\newcommand\biband{和}`没有效果

update: 我找了相关的issue mohuangrui/ucasthesis#95，但是其中提到地ucas分支好像找不到了

**Comment by zepinglee** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/blob/b624e169748b8f2886a9330508893a9dcfe89457/gbt7714-2005-numerical.bst#L67

将这里改成 `#1`，`and` 和 `et al.` 会以宏的形式输出。

https://github.com/zepinglee/gbt7714-bibtex-style/blob/b624e169748b8f2886a9330508893a9dcfe89457/gbt7714-2005-numerical.bst#L187-L199

**Comment by yangtzech** [comment]
英文作者中et al. 的确变成了等，但是等的前后还有空格。

个人理解，还应该去掉空格，不知是否正确，以及是否可以实现
1）英文作者中 等 后面的空格应该去掉
`A 等 提出了一种方法[1]。`
2）中文作者中 等 前后的空格都应该去掉
`张三 等 提出了一种方法[1]。`

**Comment by zepinglee** [comment]
姓名与“等”之间的空格是沿用国标的著者-出版年制的格式。
<img width="706" alt="Screenshot 2023-03-19 at 23 32 46" src="https://user-images.githubusercontent.com/12290822/226186739-2baa03b0-134e-4c5d-8b22-164b5604daf3.png">

如果想去掉可以将这部分
https://github.com/zepinglee/gbt7714-bibtex-style/blob/b624e169748b8f2886a9330508893a9dcfe89457/gbt7714-2005-numerical.bst#L2194-L2197
改成
```bst
        { entry.lang lang.zh =
            'skip$
            { bbl.space * }
          if$
          citation.et.al *
          #1 'namesleft :=
        }
```

`\citeauthor`后有一小段空白，而且用luatex 编译出的空白比 xetex 要大。感觉比较复杂，需要再分析 `\citeauthor` 的底层命令。

```tex
\documentclass{ctexart}

\usepackage[sort]{gbt7714}

\begin{document}

陈登原提出了一种\par
\citeauthor{4.1.2:1}提出了一种\par
\citeauthor{4.2.2:3}提出了一种\par
\citeauthor{4.4.2:9}提出了一种

% \nocite{*}
\bibliographystyle{gbt7714-numerical}
\bibliography{standard}

\end{document}
```

xetex:
<img width="176" alt="Screenshot 2023-03-19 at 23 44 12" src="https://user-images.githubusercontent.com/12290822/226187443-ac44f4e3-78ed-43c9-8ac6-7e601f3cbe9e.png">

luatex:
<img width="179" alt="Screenshot 2023-03-19 at 23 44 42" src="https://user-images.githubusercontent.com/12290822/226187474-56c9d0d6-6397-445c-90ea-f7343342c265.png">

**Comment by yangtzech** [comment]
好的，我试试。主要是中文环境下感觉留空很奇怪。

**Comment by yangtzech** [comment]
其实我发现这样用 \citeauthor{} 并不方便， \citeauthor{} 中还要放入 key，但对于英文文献而言，如果使用better bibtex导出key的话，是包含有第一个作者的姓的，直接根据key来写就好了。麻烦你了。

**Comment by zepinglee** [comment]
> `\citeauthor`后有一小段空白，而且用luatex 编译出的空白比 xetex 要大。感觉比较复杂，需要再分析 `\citeauthor` 的底层命令。

这个是因为 `natbib` 的 `\citeauthor` 和 `\citet` 在内部共用一套 `\NAT@citexnum`（`super` 上标模式），在结尾处 `\NAT@mbox{\NAT@@close}%` 生成 `\citet`（如”张三<sup>[1]</sup>“）的右方括号，但是对于 `\citeauthor` 这一行相当于空的 `\textsuperscript{}`。这个上标命令的内部目前是用数学环境 `$^{\mbox{}}$` 实现的，后面如果紧跟中文，xeCJK 就会判定为数学公式接中文，从而自动插入一段空白。

这个问题已经在最新版 `gbt7714` 修复，我在 rebase 时不小心 fixup 到 26d48d3176f388d47fe9f89971769fbb71900033 了。
