### ISSUE TITLE
中文学位论文不显示学校所在地

### ISSUE THREAD

**Issue by golgq** [zepinglee/gbt7714-bibtex-style#121]
## 编译环境
宏包版本：gbt7714 v2.1.5
标注样式：numbers 

## 描述问题
中文学位论文不显示学校所在地

bib 数据库代码：
```TeX
@phdthesis{zhushu21,
	type = {{博士}},
	title = {{考虑谐波交互的MMC模型及其在小信号稳定性分析中的应用}},
	author = {{朱蜀}},
	year = {2021},
	address = {{武汉}},
	urldate = {2022-07-02},
	langid = {chinese},
	language = {zh},
	school = {武汉大学}
}
```

截图：
![image](https://user-images.githubusercontent.com/16083870/227692624-11975cfe-8b5e-45f3-a092-8356dabfd8c4.png)

**Comment by zepinglee** [comment]
国标要显示。

<img width="729" alt="Screenshot 2023-03-25 at 12 12 03" src="https://user-images.githubusercontent.com/12290822/227695184-fa70fb3f-0d63-41c0-a171-ed2421f12e67.png">

**Comment by golgq** [comment]
@zepinglee 你好，我的意思是我想显示，但是生成的结果并未显示

**Comment by zepinglee** [comment]
我无法复现你的问题。

```tex
\documentclass{ctexart}

\begin{filecontents}[overwrite]{\jobname.bib}
@phdthesis{zhushu21,
	type = {{博士}},
	title = {{考虑谐波交互的MMC模型及其在小信号稳定性分析中的应用}},
	author = {{朱蜀}},
	year = {2021},
	address = {{武汉}},
	urldate = {2022-07-02},
	langid = {chinese},
	language = {zh},
	school = {武汉大学}
}
\end{filecontents}

\usepackage[sort]{gbt7714}

\begin{document}

\nocite{*}
\bibliographystyle{gbt7714-numerical}
\bibliography{\jobname}

\end{document}
```

<img width="537" alt="Screenshot 2023-03-25 at 12 16 31" src="https://user-images.githubusercontent.com/12290822/227695539-c475035d-38f3-4375-a4d5-bdc537be0bbb.png">

**Comment by golgq** [comment]
清除临时文件之后重新生成了一遍，已经解决问题了。感谢。
