### ISSUE TITLE
url包含doi时doi被隐藏

### ISSUE THREAD

**Issue by yangtzech** [zepinglee/gbt7714-bibtex-style#122]
如题，有的文献url已经包含doi，这个时候参考文献只会显示url而不显示doi，这样虽然会比较整洁，但会不会与其他题录格式不一致。请问这个要如何修改为不隐藏？

**Comment by zepinglee** [comment]
国标是这么要求的。

<img width="675" alt="Screenshot 2023-04-07 at 12 54 41" src="https://user-images.githubusercontent.com/12290822/230543538-2438e199-3fbe-4da9-b808-c16416a9adbb.png">

如果需要显示可以去掉这里的 ` s is.in.url or`。
<https://github.com/zepinglee/gbt7714-bibtex-style/blob/b624e169748b8f2886a9330508893a9dcfe89457/gbt7714-numerical.bst#L1559>

**Comment by yangtzech** [comment]
好的好的，谢谢
