### ISSUE TITLE
英文作者名怎么改成只有首字母大写？

### ISSUE THREAD

**Issue by Ducheese** [zepinglee/gbt7714-bibtex-style#126]
gbt7714-numerical.bst
英文作者名默认是全大写，怎么改成只有首字母大写？

**Comment by sikouhjw** [comment]
`texdoc gbt7714`, sec 7 自定义样式 or https://github.com/sikouhjw/gdutthesis/discussions/68#discussioncomment-2538305.

**Comment by zepinglee** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/blob/d730cf93a7cac207fded09a385a3e930cc4b9bdd/gbt7714-numerical.bst#L66

这里改为 `#0`。
