### ISSUE TITLE
2005多作者后逗号加'等'

### ISSUE THREAD

**Issue by Wzt1714** [zepinglee/gbt7714-bibtex-style#127]
## 编译环境
宏包版本：gbt7714 v2.1.5

## 描述问题
问题同 [#14](https://github.com/zepinglee/gbt7714-bibtex-style/issues/14)，[2005](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-2005-numerical.bst)里多作者后逗号加‘等’。 

bib 数据库代码：
```TeX
@article{相机标定方法及进展研究综述,
 author = {黄文文 and 彭小红 and 李丽圆 and 李潇雁},
 title = {相机标定方法及进展研究综述},
 journal = {激光与光电子学进展}, 
volume = {}, 
number = {}, 
year = {}, 
issn = {1006-4125},
 doi ={} 
 }
```

截图：
![image](https://user-images.githubusercontent.com/64623205/236844474-cdc73da1-d902-4ea0-866e-54e8f64f44d4.png)

**Comment by zepinglee** [comment]
<img width="853" alt="Screenshot 2023-05-08 at 22 10 34" src="https://user-images.githubusercontent.com/12290822/236846541-a62ed203-6965-446f-8028-8ea6d9872779.png">

GB/T 7714—2005 不是这么要求的？

**Comment by Wzt1714** [comment]
好的，谢谢
