### ISSUE TITLE
引用环境中添加定义/定理等

### ISSUE THREAD

**Issue by stone-zeng** [zepinglee/gbt7714-bibtex-style#128]
> ***From stone-zeng/fduthesis#303:***
>
> 目前\cite命令 \cite[Definition 1]{label 1}的编译结果是 上标{[label 1]，Definiton 1}的格式，请问该如何修改可以使定义 Definition 1和label 1一起括进方括号，[label 1, Definition 1 ].

如果直接用 `natbib` 的话，效果是

```tex
\documentclass{ctexart}
\usepackage[numbers]{natbib}
\bibliographystyle{plainnat}
\begin{document}
文字文字\cite[定理一]{曾谨言2013量子力学}文字文字
\bibliography{main}
\end{document}
```

> 文字文字 [1, 定理一] 文字文字

而用 `gbt7714` 的话，效果则是

```tex
\documentclass{ctexart}
\usepackage{gbt7714}
\begin{document}
文字文字\cite[定理一]{曾谨言2013量子力学}文字文字
\bibliography{main}
\end{document}
```

> 文字文字<sup>[1] 定理一 </sup>文字文字

<br>

所以有办法可以得到类似

> 文字文字<sup>[1, 定理一]</sup>文字文字

这样的效果吗？更进一步，如果还想标注页码的话，有没有办法实现：

> 文字文字<sup>[1, 定理一]42 </sup>文字文字

**Comment by zepinglee** [comment]
> 所以有办法可以得到类似
> 
> > 文字文字<sup>[1, 定理一]</sup>文字文字
>
> 这样的效果吗？更进一步，如果还想标注页码的话，有没有办法实现：
> 
> > 文字文字<sup>[1, 定理一]42</sup> 文字文字

这种方式跟国标不太兼容。国标要求在括号外标注页码。

<img width="781" alt="Screenshot 2023-05-25 at 17 19 20" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/ff90f307-2b23-4be1-bbea-66e8bca4bccc">



而 `natbib` 的 `\citep` 的页码和“定理一”位于同一参数，无法区分。

<img width="575" alt="Screenshot 2023-05-25 at 17 17 06" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/e1ce8fd2-5de9-4b08-95f2-bead810d3a4d">
