### ISSUE TITLE
作者年份制中出版日期如何移到期刊后面，保持类似顺序编号制的引用样式呢？

### ISSUE THREAD

**Issue by dontzb** [zepinglee/gbt7714-bibtex-style#130]
尊敬的李泽平老师您好！我们学校的参考文献格式类似numerical的格式，但是又要求中文先外文后的排列顺序，类似author-year。使用了author-year后，出版日期的位置在作者后面，又不符合要求。看了许多项目回答，仍然没有找到相关答案，请问怎么在gbt-author-year.bst的基础上编写自定义出版日期的位置使之符合要求？万分感谢！

**Comment by dontzb** [comment]
非常感谢！it works！祝您生活愉快，万事顺利！！

**Comment by dontzb** [comment]
> 

老师，这自定义好像不起作用（哭）。。

**Comment by zepinglee** [comment]
你试一下 [issue#130](https://github.com/zepinglee/gbt7714-bibtex-style/tree/issue%23130) 分支的 [/examples](https://github.com/zepinglee/gbt7714-bibtex-style/tree/issue%23130/examples)。

<img width="619" alt="Screenshot 2023-05-29 at 12 53 25" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/408abca6-12d0-4a13-b349-c19379c3f0b7">

注意需要设置 `\citestyle{numbers}`。

https://github.com/zepinglee/gbt7714-bibtex-style/blob/084a504a23f63404bcf3219e462a9d447daa5bfd/examples/gbt7714-2015-examples.tex#L8

另外基于 BibTeX 的解决方案不支持原生的中文排序，需要额外在 `key`  字段填写拼音。推荐使用 <https://github.com/hushidong/biblatex-gb7714-2015>。

**Comment by dontzb** [comment]
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/39775841/a9050d47-c98e-425f-9032-f8c0d046bc5b)

**Comment by dontzb** [comment]
老师您好！已经可以了，您太厉害了，非常感谢您的时间！还有一些有类似需要的朋友可以注意：
1、需要修改文献指示字字段的中文字符，否则会报错！
2、issue-130.bst需要放在与.tex的同层的文件，否则\bibliographystyle{issue-130}时会找不到。
再次感谢老师！请问您有收款码吗？如果您不嫌弃的话，想小小的表示一下（膜拜）！！
