### ISSUE TITLE
请问\&字符显示乱码如何解决

### ISSUE THREAD

**Issue by frwryy** [zepinglee/gbt7714-bibtex-style#131]
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/33745312/52811f03-34c7-4385-98bc-7308e497bbe1)

**Comment by zepinglee** [comment]
提供一下原始 .bib 数据？

**Comment by frwryy** [comment]
我看到bib里多了几个字符了，删掉就行了，对不起耽误您时间了。
