### ISSUE TITLE
更新文档中的第七节对参数的描述, 以及表2中的参数列表

### ISSUE THREAD

**Issue by syvshc** [zepinglee/gbt7714-bibtex-style#132]
bst 文件中已经增加了一些不只是 T/F 的参数, 如:

```
#2 'citation.et.al.min :=
#1 'citation.et.al.use.first :=
#4 'bibliography.et.al.min :=
#3 'bibliography.et.al.use.first :=
```

而第7节对参数的介绍还只是 T/F 形式的, 可以增加介绍, 并且表 2 的参数值也没有进行更新. 

![第 7 节](https://github.com/zepinglee/gbt7714-bibtex-style/assets/38098591/fb37c341-7bc3-4485-af50-f82d5f068cd6)
![表 2](https://github.com/zepinglee/gbt7714-bibtex-style/assets/38098591/9ed9049d-1ca1-43ca-9b22-62cbcf82c5bf)

**Comment by zepinglee** [comment]
原本的设计中，这部分的参数不是给终端用户使用的，而是给模板作者修改的。所以写得不是很详细。

改天把每个选项分段写一下吧。

**Comment by syvshc** [comment]
> 原本的设计中，这部分的参数不是给终端用户使用的，而是给模板作者修改的。所以写得不是很详细。
> 
> 改天把每个选项分段写一下吧。

感谢 :)
