### ISSUE TITLE
gbt7714-numerical  参考文献引用如何使用平标，并且添加方括号

### ISSUE THREAD

**Issue by Annsas** [zepinglee/gbt7714-bibtex-style#133]

**Comment by zepinglee** [comment]
<img width="805" alt="Screenshot 2023-06-06 at 17 29 52" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/8d16504d-75be-4cd4-8190-9066d77ef600">

**Comment by Annsas** [comment]
已解决，感谢





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zeping Lee ***@***.***&gt;
发送时间: 2023年6月6日 17:30
收件人: zepinglee/gbt7714-bibtex-style ***@***.***&gt;
抄送: Sarah ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zepinglee/gbt7714-bibtex-style] gbt7714-numerical  参考文献引用如何使用平标，并且添加方括号 (Issue #133)

**Comment by Annsas** [comment]
尊敬的李老师：
&nbsp; &nbsp; &nbsp; 您好，还有一个问题想请教解决一下，如图所示，不知为何，间距过大，其他的均正常
&nbsp; &nbsp; &nbsp;






528497479
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zepinglee/gbt7714-bibtex-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zepinglee/gbt7714-bibtex-style] gbt7714-numerical  参考文献引用如何使用平标，并且添加方括号 (Issue #133)

**Comment by sikouhjw** [comment]
> 尊敬的李老师： &nbsp; &nbsp; &nbsp; 您好，还有一个问题想请教解决一下，如图所示，不知为何，间距过大，其他的均正常 

你的图未发送成功。

**Comment by Annsas** [comment]
红框处间距过大，不知如何调整，马赛克部分为文字，可忽略






528497479
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zepinglee/gbt7714-bibtex-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月12日(星期一) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zepinglee/gbt7714-bibtex-style] gbt7714-numerical  参考文献引用如何使用平标，并且添加方括号 (Issue #133)





  
尊敬的李老师： &nbsp; &nbsp; &nbsp; 您好，还有一个问题想请教解决一下，如图所示，不知为何，间距过大，其他的均正常
  
你的图未发送成功。

**Comment by Annsas** [comment]
红框处间距过大，不知如何调整，马赛克部分为文字，可忽略
![jianju](https://github.com/zepinglee/gbt7714-bibtex-style/assets/29617619/06bd0b21-8e3e-43d1-8e1b-ae3133b31f15)

**Comment by zepinglee** [comment]
> 红框处间距过大，不知如何调整，马赛克部分为文字，可忽略 ![jianju](https://user-images.githubusercontent.com/29617619/245097773-06bd0b21-8e3e-43d1-8e1b-ae3133b31f15.jpg)

1. 跟本项目有什么联系？
2. 有相关的问题新开 issue 讨论。
