### ISSUE TITLE
参考文献如何正确插入“@standard”格式？（GB/T 7714—2015）

### ISSUE THREAD

**Issue by stone-faced** [zepinglee/gbt7714-bibtex-style#135]
## 编译环境
老师您好，您说的宏包版本和标注样式我不是太懂什么意思，我使用的是thuthesis的模板，可能是下面这些内容吧
%参考文献使用 BibTeX + natbib 宏包
% 顺序编码制
\usepackage[sort]{natbib}
\bibliographystyle{thuthesis-numeric}

## 描述问题
自己的使用standard样式插入国家标准，出现两个问题：1参考文献显示的内容缺少“发行机构” 2 各元素顺序不对
我期望的顺序是“机构+国标编号+标准名称+地址+出版社+年份”，而运行出来的是“标准名称+国标编号+地址+出版社+年份”

bib 数据库代码：
```TeX
@Standard{架空输电线路设计规范,
	title= { 110$\sim$750kV架空输电线路设计规范},
	organization = {中华人民共和国住房和城乡建设部},
	%institution={中华人民共和国国家质量监督检验检疫总局},
	number = {GB 50545-2010},
	year = {2010},
	address = {北京},
	publisher = {中国计划出版社}
}
```

截图：
![1](https://github.com/zepinglee/gbt7714-bibtex-style/assets/59330891/dfd5d966-d5e2-4d74-aed5-2519cb03313d)

**Comment by stone-faced** [comment]
老师  我能明白您的意思  可能是学校给的word模板里面错了吧  如下图所示
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/59330891/b940acf8-6a1f-4768-b118-489851592979)
如果是两个单位共同发行的，我直接author中间加一个and应该就可以吧？

**Comment by zepinglee** [comment]
> 老师 我能明白您的意思 可能是学校给的word模板里面错了吧 如下图所示 ![image](https://user-images.githubusercontent.com/59330891/244852174-b940acf8-6a1f-4768-b118-489851592979.png) 

研究生的 word 模板是吧？我去联系一下研究生院。

其实第 21 条文献的格式跟国标一致。

<img width="740" alt="Screenshot 2023-06-10 at 16 48 22" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/ca074765-a8fd-43bf-b7fe-549429e7b4aa">

> 如果是两个单位共同发行的，我直接author中间加一个and应该就可以吧？

是的。不过从 GB/T 7714—2015 的示例来看，author 一般写“归口单位”。比如 A.6 节示例文献 [1]：

https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D7D040D3A7E05397BE0A0AB82A

<img width="812" alt="Screenshot 2023-06-10 at 16 54 11" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/22e4a7dd-abcf-469a-b886-8aba3fe914f9">

**Comment by stone-faced** [comment]
是的  老师  研究生的word论文模板    谢谢老师  我现在“standard”文献引用格式问题在您的帮助下已经解决了！
