### ISSUE TITLE
如何在目录后面增加图索引以及表索引？

### ISSUE THREAD

**Issue by JiangHe96** [zepinglee/gbt7714-bibtex-style#136]

**Comment by JiangHe96** [comment]
像这样的效果，论文的每一张图都有像目录那样的链接：![微信图片_20230703200955](https://github.com/zepinglee/gbt7714-bibtex-style/assets/69843863/3b414c03-7369-4841-817c-1272306564ea)

**Comment by zepinglee** [comment]
`\listoffigures`, `\listoftables`

与本项目无关的内容可以考虑发到 <https://github.com/CTeX-org/forum/> 或 <https://ask.latexstudio.net/>。

**Comment by JiangHe96** [comment]
谢谢 麻烦啦
