### ISSUE TITLE
章节间距不知如何调整

### ISSUE THREAD

**Issue by Annsas** [zepinglee/gbt7714-bibtex-style#137]
## 编译环境
宏包版本：gbt7714 
标注样式：super / numbers 

## 描述问题
章节间距过大，不知如何调整
如截图所示，2.2前间距较大

截图：
![截屏2023-07-04 00 05 37_副本](https://github.com/zepinglee/gbt7714-bibtex-style/assets/29617619/d42e97a4-218e-4d12-a65f-8c6941c4836f)

**Comment by zepinglee** [comment]
1. 这个问题与本宏包无关，建议发到 <https://github.com/CTeX-org/forum/> 或 <https://ask.latexstudio.net/>。
2. 描述问题时给出复现问题的代码，参考 [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)。
