### ISSUE TITLE
参考文献显示出不来？

### ISSUE THREAD

**Issue by whfei561** [zepinglee/gbt7714-bibtex-style#140]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：numbers

## 描述问题
```tex
\documentclass{ctexart}

\usepackage[sort]{gbt7714}
\bibliographystyle{gbt7714-numerical}

\begin{document}
	
	\cite{Hodges}sfsfdsfdfssdf dsf 
	\bibliography{Refer}
	
\end{document}
```
以上是代码，我把.sty和.bst复制到同一目录下，但参考问显示不出来
bib 数据库代码：
```bibtex
@article{,
  title={Hodges-Lehmann Optimality for Testing Moment Conditions},
  author={ Canay, Ivan A  and  Otsu, Taisuke },
  journal={Journal of Econometrics},
  volume={171},
  number={1},
  year={2011},
}
```

截图：
![1697359667010](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/89b64a14-5a77-454f-b946-32224d52f781)
![1697359700043](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/ba99732e-56ca-447f-adbb-859dfd9322b6)

**Comment by sikouhjw** [comment]
1. 确保 bib 文件在工作目录下
2. bib 数据库里的文献没有 label
3. 你引用的是 `Hodges`，与 bib 的对不上
4. 确保运行了 bibtex

**Comment by zepinglee** [comment]
```bib
@article{,
```
改成
```bib
@article{Hodges,
```

**Comment by whfei561** [comment]
刚才我复制错了，bib没问题，@article{Hodges,
  title={Hodges-Lehmann Optimality for Testing Moment Conditions},
  author={ Canay, Ivan A  and  Otsu, Taisuke },
  journal={Journal of Econometrics},
  volume={171},
  number={1},
  year={2011},
}
还是不行，是我没有安装gbt7714这个宏包吗？

![1697361187335](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/67c5459e-0d3c-40fa-a93f-bca69f5789f0)

**Comment by zepinglee** [comment]
> 刚才我复制错了，bib没问题，@Article{Hodges, title={Hodges-Lehmann Optimality for Testing Moment Conditions}, author={ Canay, Ivan A and Otsu, Taisuke }, journal={Journal of Econometrics}, volume={171}, number={1}, year={2011}, } 还是不行，是我没有安装gbt7714这个宏包吗？
> 
> ![1697361187335](https://user-images.githubusercontent.com/44922528/275316445-67c5459e-0d3c-40fa-a93f-bca69f5789f0.png)

> Sorry---you've exceeded BibleX's single function space 100

旧版的 bibtex 没有分配足够的空间，建议用新版 MiKTeX 的 bibtex.
