### ISSUE TITLE
我想要参考文献中作者的首字母大写，而不是所有字母大写

### ISSUE THREAD

**Issue by whfei561** [zepinglee/gbt7714-bibtex-style#141]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
国标要求
Walls S C, Barichivich W J, Brown M E. Drought, deluge and declines: the impact of precipitation extremes on amphibians in a changing climate[J]. Biology, 2013, 2(1): 399-418.
而编译的结果是

截图：
![1697374390198](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/ba0fe5e5-acdd-457b-97b4-22bf0ff32e9a)，

请问一下作者应该怎么改？？？

**Comment by zepinglee** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714-numerical.bst#L66

这里改成 `#0`。

**Comment by Stitchiey** [comment]
> https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714-numerical.bst#L66
> 
> 这里改成 `#0`。

您好，我尝试过更改.bst文件以后再使用“latex gbt7714.ins”命令重新编译，然而生成的.sty文件仍然和初始文件一样，包括更改过的.bst文件也被撤回到了初始版本，请问应该如何解决？

**Comment by zepinglee** [comment]
> > https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714-numerical.bst#L66
> > 
> > 这里改成 `#0`。
> 
> 您好，我尝试过更改.bst文件以后再使用“latex gbt7714.ins”命令重新编译，然而生成的.sty文件仍然和初始文件一样，包括更改过的.bst文件也被撤回到了初始版本，请问应该如何解决？

`latex gbt7714.ins` 会覆盖 `.bst` 文件。所以可以在 `.dtx` 文件中修改对应的内容，或不执行 `.ins`，直接使用修改后的 `.bst` 文件。

**Comment by Stitchiey** [comment]
> > > https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714-numerical.bst#L66
> > > 
> > > 这里改成 `#0`。
> > 
> > 
> > 您好，我尝试过更改.bst文件以后再使用“latex gbt7714.ins”命令重新编译，然而生成的.sty文件仍然和初始文件一样，包括更改过的.bst文件也被撤回到了初始版本，请问应该如何解决？
> 
> `latex gbt7714.ins` 会覆盖 `.bst` 文件。所以可以在 `.dtx` 文件中修改对应的内容，或不执行 `.ins`，直接使用修改后的 `.bst` 文件。

因为我是用的是overleaf，仅支持`.sty`或者`.cls`。因此我尝试在`.dtx`文件中修改对应内容，即
https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714.dtx#L2073
修改为
`        { t #0 "{vv~}{ll}{ f{~}}" format.name$
`
然后使用`latex gbt7714.ins`命令，得到`.sty`文件。但问题依旧。我不清楚是因为我找到`.dtx`文件中错误的对应内容还是别的原因。请问这样应该怎样解决？

**Comment by sikouhjw** [comment]
> 或不执行 .ins，直接使用修改后的 .bst 文件。

修改 bst 后**不要**执行 `.ins`

**Comment by zepinglee** [comment]
> 因为我是用的是overleaf，仅支持`.sty`或者`.cls`。

你直接上传一份 `.bst` 文件到 overleaf，然后进行修改就可以了。

> 因此我尝试在`.dtx`文件中修改对应内容，即
> 
> https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714.dtx#L2073
> 
> 
> 修改为
> ` { t #0 "{vv~}{ll}{ f{~}}" format.name$`

需要修改的不是这里，而是下面这行。

https://github.com/zepinglee/gbt7714-bibtex-style/blob/5ba4dcd8c4443a2cd0398897b5c5a7322a66db88/gbt7714.dtx#L946

> 然后使用`latex gbt7714.ins`命令，得到`.sty`文件。但问题依旧。我不清楚是因为我找到`.dtx`文件中错误的对应内容还是别的原因。请问这样应该怎样解决？

这行会生成到 `.bst` 文件，不是 `.sty` 文件。
