### ISSUE TITLE
对“参考文献”进行章节编号

### ISSUE THREAD

**Issue by Stitchiey** [zepinglee/gbt7714-bibtex-style#142]
## 编译环境
宏包版本：gbt7714 v2.1.5
标注样式：super

## 描述问题
当我使用gbt7714引用宏包之后，
“\usepackage{xpatch}
\xpatchcmd{\thebibliography}{\section*}{\section}{}{}”
的命令即失效，无法给“参考文献”进行章节编号；但若不引用该宏包，上述命令可正常作用，给“参考文献”进行章节编号。请问此问题应该如何解决？

**Comment by zepinglee** [comment]
> ## 编译环境
> 宏包版本：gbt7714 v2.1.5 标注样式：super
> 
> ## 描述问题
> 当我使用gbt7714引用宏包之后， “\usepackage{xpatch} \xpatchcmd{\thebibliography}{\section*}{\section}{}{}” 的命令即失效，无法给“参考文献”进行章节编号；但若不引用该宏包，上述命令可正常作用，给“参考文献”进行章节编号。请问此问题应该如何解决？

`gbt7714` 调用的 `natbib` 修改了 `thebibliography` 的定义，所以会 patch 失败。建议在 `\xpatchcmd` 最后一个参数中报错，有助于及时发现问题。

`natbib` 提供了一套更简单的修改办法，即 `\renewcommand\bibsection{\section{\refname}}`。
<img width="762" alt="Screenshot 2023-10-24 at 13 34 19" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/44dac670-8dcb-4654-805d-1dd3a1b72abb">
