### ISSUE TITLE
将url与论文期刊链接到一起呢

### ISSUE THREAD

**Issue by dandanDDdan** [zepinglee/gbt7714-bibtex-style#144]
请问老师，怎么实现将url与论文期刊链接到一起呢

**Comment by zepinglee** [comment]
没明白你的意思，举个例子？

**Comment by dandanDDdan** [comment]
<img width="323" alt="1699195252395" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/102354215/3571821d-4a75-4753-9cb5-9016a2da5cfc">

**Comment by dandanDDdan** [comment]
老师您好，就像这样，它是把文章的链接与期刊名称链接到一起了

**Comment by zepinglee** [comment]
> 老师您好，就像这样，它是把文章的链接与期刊名称链接到一起了

目前只实现了将链接放在文章标题上，放在期刊上需要再改改。

**Comment by zepinglee** [comment]
89c45ee 中添加了 `journal.title` 选项。

https://github.com/zepinglee/gbt7714-bibtex-style/blob/89c45eec22cd5c5bd5b3fe34a973eef50481290d/gbt7714-numerical.bst#L82
