### ISSUE TITLE
引用顺序

### ISSUE THREAD

**Issue by mengzhu0308** [zepinglee/gbt7714-bibtex-style#146]
我在文章中第一处引用文献，但是文章中文献编号不是1。如何按照论文中文献引用先后顺序编号了？

**Comment by mengzhu0308** [comment]
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/75422140/da1d6cce-b462-43ca-85f4-ff9b635acba4)
论文中，我是第一处引用，但是编号却是5.

**Comment by sikouhjw** [comment]
给代码
