### ISSUE TITLE
引用顺序问题

### ISSUE THREAD

**Issue by mengzhu0308** [zepinglee/gbt7714-bibtex-style#147]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers 

## 描述问题
希望文献按引用顺序编号，即下列文献在论文的引用编号应为[1]，但是编译的结果是[5]

bib 数据库代码：
```TeX
@article{McCulloch_1934_LogicalCalculus,
 author = {McCulloch, W. S. and Pitts, W.},
 doi = {10.1007/BF02478259},
 journal = {The Bulletin of Mathematical Biophysics},
 number = {4},
 pages = {115-133},
 title = {A Logical Calculus of the Ideas Immanent in Nervous Activity},
 volume = {5},
 year = {1943}
}
```

截图：

**Comment by mengzhu0308** [comment]
此处改正一下：宏包版本：gbt7714 v2.0

**Comment by mengzhu0308** [comment]
请问这个问题该如何解决呀？

**Comment by mengzhu0308** [comment]
论文中也是按照readme的要求这样写的：
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}

**Comment by sikouhjw** [comment]
编译方式：`latexmk -pdf`
```tex
\begin{filecontents*}{\jobname.bib}
@article{McCulloch_1934_LogicalCalculus,
  author  = {McCulloch, W. S. and Pitts, W.},
  doi     = {10.1007/BF02478259},
  journal = {The Bulletin of Mathematical Biophysics},
  number  = {4},
  pages   = {115-133},
  title   = {A Logical Calculus of the Ideas Immanent in Nervous Activity},
  volume  = {5},
  year    = {1943}
 }
\end{filecontents*}

\documentclass{article}
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
\begin{document}
\cite{McCulloch_1934_LogicalCalculus}
\bibliography{\jobname.bib}
\end{document}
```
![图片](https://github.com/zepinglee/gbt7714-bibtex-style/assets/49770925/43ce7051-137d-430b-abbe-2df37fad9a8c)

**Comment by mengzhu0308** [comment]
谢谢回复，但是我改为latexmk编译会报错，只能用xelate编译。

**Comment by mengzhu0308** [comment]
我的文件类是这个：
\documentclass[
hyperref,% 标签和超链接，放在这里，防止乱码。
UTF-8,% 指明编码文档时使用的编码格式。
a4paper,%
openany,% 
oneside,% 
no-math,%
AutoFakeBold,% 中文字体加粗。
zihao=-4,% 
fontset=windows,%
linespread=1.39]{ctexbook} % ctex*文档类会自动调用fontspec宏包、xeCJK宏包等。

**Comment by zepinglee** [comment]
无法复现你的问题。这个 numeric 样式默认就是按照引用顺序的。

可能是你的引用出现在了目录中，被误认为是先引用的。建议检查 [1] 号引用的位置，并给出可复现问题的代码。

**Comment by mengzhu0308** [comment]
谢谢您的回复。我仔细检查了，应该没有在目录中出现引用。后面，我是这样解决的。先通过latexmk编译生成.bbl文件，然后用xelatex编译，并删除除.bbl之外的辅助生成文件，文献顺序正常引用了。

**Comment by mengzhu0308** [comment]
用latexmk编译，文献顺序引用，但\setCJKmainfont{SimSun}	% 设置中文字体为宋体
\setmainfont{Times New Roman} % 设置英文字体为Times New Roman会报错，用xelatex编译，文献无法顺序引用，但不会报错，所以取巧各自编译了一下。

**Comment by zepinglee** [comment]
> 用latexmk编译，文献顺序引用，但\setCJKmainfont{SimSun} % 设置中文字体为宋体 \setmainfont{Times New Roman} % 设置英文字体为Times New Roman会报错，用xelatex编译，文献无法顺序引用，但不会报错，所以取巧各自编译了一下。

你描述的情况非常奇怪。建议给出完整的 [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Comment by mengzhu0308** [comment]
好的，稍等一会儿。

**Comment by mengzhu0308** [comment]
我刚才仔细检查了一下，确实提前出现在目录中了

**Comment by mengzhu0308** [comment]
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/75422140/fa3f6b6a-53e5-4fca-a606-4deb7fdd763d)

**Comment by mengzhu0308** [comment]
意思是说，我应该解决的是插图目录中提前出现文献引用怎么办？

**Comment by mengzhu0308** [comment]
意思是，各种目录应该最后生成，从而保证引用顺序。

**Comment by mengzhu0308** [comment]
谢谢您的回复和帮助呀！

**Comment by zepinglee** [comment]
一种是使用 [`notoccite`](https://ctan.org/pkg/notoccite)，另一种是 `\section[]{}` 的方括号中去掉 `\cite` 重写一遍。

**Comment by mengzhu0308** [comment]
收到！
