### ISSUE TITLE
能否修改bst文件，使参考文献中不含doi和url

### ISSUE THREAD

**Issue by youmei** [zepinglee/gbt7714-bibtex-style#148]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：numbers

## 描述问题
请问能否在不修改bib文件的前提下，修改bst文件，生成不含doi和url内容的参考文献条目
使用bibtex4word，texlive2023，gbt7714-numerical.bst

bib 数据库代码：
```TeX
@Article{HeZhiyi2020#092,
       author   = {He Zhiyi and Shao Haidong and Jing Lin and Cheng Junsheng and Yang Yu},
       journal  = {Measurement},
       title    = {Transfer fault diagnosis of bearing installed in different machines using enhanced deep auto-encoder},
       year     = {2020},
       issn     = {0263-2241},
       pages    = {107393},
       volume   = {152},
       doi      = {https://doi.org/10.1016/j.measurement.2019.107393},
       keywords = {Enhanced deep auto-encoder model, Transfer diagnosis, Limited labeled information, Bearing fault, Different machines},
       url      = {https://www.sciencedirect.com/science/article/pii/S0263224119312606},
}
```

**Comment by sikouhjw** [comment]
![图片](https://github.com/zepinglee/gbt7714-bibtex-style/assets/49770925/9fb84a49-5be5-4506-ab5c-5a8666b3e946)
看一眼手册吧

**Comment by youmei** [comment]
谢谢指点。
方法是修改bst文件中，
FUNCTION {load.config}
{
......
  #1 'show.url :=
  #1 'show.doi :=
}
把#1改为#0

**Comment by rachellyl** [comment]
最新下载的版本改了bst文件中的show.doi和show.url的值。最后文档还是输出了doi

**Comment by rachellyl** [comment]
test2.tex: 错误: : File ended while scanning use of \kvsetkeys.
ctexart.cls: 警告: : UTF8 will be used as the default encoding.报错信息

**Comment by rachellyl** [comment]
> `\documentclass{ctexart}%ctexbook,ctexrep
\usepackage[top = 2.54cm, bottom = 2.54cm, left = 3.18cm, right = 3.18cm]{geometry}%处理页面宏包
\usepackage{hyperref}%文献引用的跳转
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}%使用国标2015-中文引用
\hypersetup{
		colorlinks=true,
		linkcolor=black,%普通文本链接改为黑色
		citecolor=black,%引用参考文献的框将默认绿色改为黑色
		urlcolor=black,%文档网址的颜色设置为黑色}
%文稿区
\begin{document}
	传统的穿梭车调度主要集中在路径规划、任务分配以及时间优化方面。在路径规划方面，杨玮\cite{JSJJ201707020}为解决堆垛机复合作业三维空间路径规划问题提出混合蚁群算法，并用实例分析证实了该混合算法相较于单一蚁群算法有更好的全局性；占翔南针【】对四向库中多台穿梭车同时作业易造成冲突死锁的问题，采用Hopcroft-Tarjan算法制定路径，以最小化作业时间为目标构建模型并设计混合遗传对该模型进行求解。李军涛【】提出穿梭车和提升机协同作业并考虑同层同巷道的任务执行冲突，建立能耗及作业时间最小的双目标优化模型并提出改进的麻雀搜索算法，通过多维仿真验证了模型和算法的有效性。
	\bibliography{reference}
\end{document}`

**Comment by zepinglee** [comment]
> test2.tex: 错误: : File ended while scanning use of \kvsetkeys. ctexart.cls: 警告: : UTF8 will be used as the default encoding.报错信息

这些错误跟 gbt7714 无关。

实际上，是与 `\hypersetup{` 配对的右括号 `}` 被错误地注释掉了。

另外，下次有问题时新开 issue 讨论。
