### ISSUE TITLE
关于参考文献样式gbt7714-author-year出版年的显示位置错误的问题

### ISSUE THREAD

**Issue by ACienZ** [zepinglee/gbt7714-bibtex-style#149]
## 编译环境
宏包版本：v2.1.5  
标注样式：author-year  

## 描述问题  
国标要求专著的著录格式：  

[序号] 主要责任者. 题名: 其他题名信息[文献类型标志/文献载体标识]. 其他责任者. 版本项. 出版地: 出版者, 出版年: 引文页码[引用日期]. 获取和访问路径. 数字对象唯一标识符.    

而如果bibliographystyle选择{gbt7714-author-year}后，  
使用XeLaTex -> BibTex -> XeLaTex*2 编译，  
结果的**出版年份**位置会出现问题：

例如：
- 使用\bibliographystyle{gbt7714-numerical}结果:   
    Rousseau J J. Emile[M]. A. Belin, 1817.  
- 使用\bibliographystyle{gbt7714-author-year}结果：
    ROUSSEAU J J, 1817. Emile: Vol. 2[M]. A. Belin.

bib 数据库代码：
```
@book{rousseau1817emile,
  title={Emile},
  author={Rousseau, Jean-Jacques},
  volume={2},
  year={1817},
  publisher={A. Belin}
}
```

这里是一个例子：
https://github.com/ACienZ/GBT77142015_author_year_discuss

**Comment by zepinglee** [comment]
<img width="808" alt="Screenshot 2023-12-10 at 00 03 45" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/f5a1bfd8-0298-4080-8d22-fe212a653fbc">

**Comment by ACienZ** [comment]
非常感谢您的回答，因为我的疏忽浪费您的时间实在抱歉。
学校要求的参考文献格式是著者-出版年制，但是末尾的参考文献表却是顺序编码制，所以下意识以为是bug，没有在GB/T7714-2015标准中进行确认。
感谢您的指正。

**Comment by zepinglee** [comment]
许多期刊/学校声称使用 GB/T 7714 格式，但是绝大部分都跟这份标准有些差异。
