### ISSUE TITLE
你好，我想问一下，有的文章没有发表，我想用arxiv结尾，但好像出现问题了

### ISSUE THREAD

**Issue by whfei561** [zepinglee/gbt7714-bibtex-style#151]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：numbers

## 描述问题
有的文章没有发表，我想用arxiv结尾，但好像出现问题了

bib 数据库代码：
```TeX
@article{2015,
  title={Problem},
  author={Zhang, San},
  journal={arXiv:XXXXXX},
  volume={},
  number={},
  year={2015}
}
```

显示的结果是
Zhang S, Problem[A],2015

哪里出问题了呢？
![1703725886742](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/3a680265-69ce-47af-a0e4-c757c25ef586)

我想要最后这样的效果
Zhang S, Problem[J],arxiv: XXXXXX,2015.
或者其他符合gbt7714的格式，把arxiv显示出来

**Comment by zepinglee** [comment]
国标没有规定预印本的格式，也没有示例。但是参考国外的 APA, Chicago 等体例，预印本的格式更接近 monograph（例如图书）格式，所以不能用期刊文章 `@article`。建议参考 arXiv 官方导出的 BibTeX 格式。

<img width="628" alt="Screenshot 2023-12-28 at 10 54 46" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/9cbef400-72bc-458f-8b26-221938d8cb12">

**Comment by whfei561** [comment]
谢谢你，我解决了这个问题

**Comment by zepinglee** [comment]
> 谢谢你，但想问问你，我现在文章后面还是[A],可不可以改成[J]???

预印本不是期刊（Journal）文章，所以用“[J]”是不合理的。见 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/89#issuecomment-950295152> 的讨论。

**Comment by whfei561** [comment]
好的，非常感谢回答
