### ISSUE TITLE
First/Middle Name 的增补拉丁文首字母可能无法正常显示

### ISSUE THREAD

**Issue by ajz34** [zepinglee/gbt7714-bibtex-style#152]
## 编译环境

宏包版本：gbt7714 v2.1.5 (shipped with TexLive 2023)
标注样式：numbers

## 描述问题

当作者姓名中，出现 first name 或 middle name 的字母是拉丁文、但又非 ASCII 码的情况时 (如 Éric Brémond 的字母 É)，可能 gbt7714 包难以正确地将首字母显示出来。在正常情况下会显示空格；一些库会显示黑色菱形内有反白问号的字符。
这与 https://github.com/zepinglee/gbt7714-bibtex-style/issues/145 所提到的西文姓氏中含如 é 到 É 的大小写转换问题并不相同。

该问题并非紧要的问题，是存在解决办法的。如果字母的拉丁文可以通过 ASCII 码的 TeX 代码实现 (如 `{\'E}` 实现字母 É)，那么显示上就正常了。我自己也没有碰到更复杂的情况 (譬如 TeX 代码也搞不定的字母)，所以于我而言使用 gbt7714 上还没有遇到困难。

## 复现代码

TeX 文件代码：

```TeX
% !TEX root=tmp.tex

\documentclass{ctexart}
\usepackage{gbt7714}
\usepackage{natbib}
\bibliographystyle{gbt7714-numerical}

\begin{document}

Wrong version here: \citenum{wrong-ver}.
Correction version here: \citenum{correct-ver}.

\bibliography{tmp.bib}
\end{document}
```

bib 文件代码：

```bib
@article{wrong-ver,
 author = {BRÉMOND, ÉRIC and LI, HANWEI and PÉREZ-JIMÉNEZ, ÁNGEL JOSÉ and SANCHO-GARCÍA, JUAN CARLOS and ADAMO, CARLO},
 doi = {10.1063/5.0087586},
 journal = {J. Chem. Phys.},
 number = {16},
 pages = {161101},
 title = {Tackling an accurate description of molecular reactivity with double-hybrid density functionals},
 volume = {156},
 year = {2022}
}

@article{correct-ver,
 author = {BRÉMOND, {\'E}RIC and LI, HANWEI and PÉREZ-JIMÉNEZ, {\'A}NGEL JOSÉ and SANCHO-GARCÍA, JUAN CARLOS and ADAMO, CARLO},
 doi = {10.1063/5.0087586},
 journal = {J. Chem. Phys.},
 number = {16},
 pages = {161101},
 title = {Tackling an accurate description of molecular reactivity with double-hybrid density functionals},
 volume = {156},
 year = {2022}
}
```

截图：

<img width="592" alt="Screenshot 2024-01-20 124517 - 副本" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/21327872/1cad4712-7233-41c8-9a4f-34cabe73b9f8">

**Comment by zepinglee** [comment]
这个应该没什么办法，BibTeX 不支持 Unicode。所以

**Comment by ajz34** [comment]
哈哈 😹 了解！
