### ISSUE TITLE
关于arXiv的引用格式

### ISSUE THREAD

**Issue by whfei561** [zepinglee/gbt7714-bibtex-style#155]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
我们老师要求axriv的文章为"[J]"，但我引用的格式不管怎么改，只能得到"[A]”

想请问您，怎么更改bst文件，使得arxiv 的文章可以展现出这样的结果：
“XXX. XXXXXXXXXX[J]. ArXiv preprint arXiv:xxxxxx.”

**Comment by sikouhjw** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/issues/89#issuecomment-950295152
https://github.com/zepinglee/gbt7714-bibtex-style/issues/151#issuecomment-1871665345

**Comment by zepinglee** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/blob/89c45eec22cd5c5bd5b3fe34a973eef50481290d/gbt7714-numerical.bst#L1987-L1991

这一段改为 `{ journal.article }`。

**Comment by Morris-Lucifer** [comment]
> [gbt7714-bibtex-style/gbt7714-numerical.bst](https://github.com/zepinglee/gbt7714-bibtex-style/blob/89c45eec22cd5c5bd5b3fe34a973eef50481290d/gbt7714-numerical.bst#L1987-L1991)
> 
> Lines 1987 to 1991 in [89c45ee](/zepinglee/gbt7714-bibtex-style/commit/89c45eec22cd5c5bd5b3fe34a973eef50481290d)
> 
>  { check.arxiv.preprint 
>      'preprint 
>      'journal.article 
>    if$ 
>  } 
> 这一段改为 `{ journal.article }`。

请问为什么我按照这个改完了还是[A]呢？尝试修改
```
FUNCTION {check.arxiv.preprint}
{ #1 #5 substring$ "l" change.case$ "aaaaa" =
    { #1 }
    { #0 }
  if$
}
```
编译后也仍然是[A]，已确认删除过bbl和aux文件

**Comment by zepinglee** [comment]
> 改了下判断的顺序

@Morris-Lucifer 有道理，我也改一下仓库中的 bst 文件。

你的 `.bib` 文件是从 Zotero 的 BBT 导出的吧？

**Comment by Morris-Lucifer** [comment]
对，用better bibtex插件导出的
