### ISSUE TITLE
关于运行出错的问题

### ISSUE THREAD

**Issue by whfei561** [zepinglee/gbt7714-bibtex-style#156]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
    \usepackage[numbers]{gbt7714}
	\bibliographystyle{gbt7714-numerical}
	\bibliography{refer}

bib 数据库代码：
```TeX
@article{bai2008large,
  title={Large sample covariance matrices without independence structures in columns},
  author={Bai, Zhidong and Zhou, Wang},
  journal={Statistica Sinica},
  pages={425--442},
  volume={18},
  number={2},
  year={2008}
}
```

截图：
出现90个错误，描述为：
This is BibTeX, Version 0.99d (TeX Live 2023)
The top-level auxiliary file: xxx.aux
The style file: gbt7714-numerical.bst
Illegal, another \bibstyle command---line 545 of file xxxx.aux
 : \bibstyle
 :          {gbt7714-numerical}
I'm skipping whatever remains of this command
Database file #1: refer.bib
ptr=1, stack=
Statistica Sinica
---the literal stack isn't empty for entry bai1996effect
while executing---line 2455 of file gbt7714-numerical.bst
………………………………………………
![1709109037154](https://github.com/zepinglee/gbt7714-bibtex-style/assets/44922528/656d6898-9b7d-4b66-be37-cb76a3c8a13c)

这个错误是什么意思，怎么更改呢？

**Comment by sikouhjw** [comment]
😅请问 `gbt7714-unsrt` 是从哪抄来的

**Comment by sikouhjw** [comment]
`texdoc gbt7714`
> 从 v2.0 版本开始（2020-03-04），用户必须在文档中使用 \biblilographystyle
> 命令选择参考文献样式，如 gbt7714-numerical 或 gbt7714-author-year。在早期
> 的版本中，选择文献样式的方法是将 numbers 或 super 等参数传递给 gbt7714，而不
> 能使用 \bibliographystyle。这跟标准的 LaTeX 接口不一致，所以将被弃用。

```tex
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
```

**Comment by zepinglee** [comment]
旧版（v1.x）在 `gbt7714` 宏包中设置了 `\bibliographystyle`，导致了重复。

建议将宏包更新至最新版。

**Comment by whfei561** [comment]
> `texdoc gbt7714`
> 
> > 从 v2.0 版本开始（2020-03-04），用户必须在文档中使用 \biblilographystyle 命令选择参考文献样式，如 gbt7714-numerical 或 gbt7714-author-year。在早期 的版本中，选择文献样式的方法是将 numbers 或 super 等参数传递给 gbt7714，而不 能使用 \bibliographystyle。这跟标准的 LaTeX 接口不一致，所以将被弃用。
> 
> ```
> \usepackage{gbt7714}
> \bibliographystyle{gbt7714-numerical}
> ```

谢谢

**Comment by whfei561** [comment]
> 旧版（v1.x）在 宏包中设置了 ，导致了重复。`gbt7714``\bibliographystyle`
> 
> 建议将宏包更新至最新版。

感谢
