### ISSUE TITLE
Overleaf无法使用

### ISSUE THREAD

**Issue by Mashirops** [zepinglee/gbt7714-bibtex-style#158]
## 编译环境
宏包版本：gbt7714 v2.0 
编译环境：Overleaf
标注样式：\textsuperscript{\cite{xxx}}，顺序标注

## 描述问题
Overleaf编译之后不会出现对应的参考文献，我直接\usepackage{gbt7714}，然后\bibliographystyle{gbt7714-numerical}，但是最终没有任何参考文献出现，希望大佬指点一下，感谢！！
![捕获1](https://github.com/zepinglee/gbt7714-bibtex-style/assets/58142289/dc86a798-eac9-41b5-b918-3c7fb1236e2d)
![捕获2](https://github.com/zepinglee/gbt7714-bibtex-style/assets/58142289/aa9302cf-973a-4b40-93f2-b99d2d37ec2c)
![捕获3](https://github.com/zepinglee/gbt7714-bibtex-style/assets/58142289/71240f87-b247-4c57-b4fb-47aa0c83f326)

**Comment by sikouhjw** [comment]
不需要 `\textsuperscript{\cite{xxx}}`，仅需要 `\cite`

**Comment by Mashirops** [comment]
感谢即使回复，我用的编译器是XeLatex
\textsuperscript是学校要求的格式，而且\cite也没有出来结果，我也很迷茫......

**Comment by zepinglee** [comment]
建议给出复现的代码 https://en.wikipedia.org/wiki/Minimal_reproducible_example。

**Comment by Mashirops** [comment]
好的，我提供了一个Overleaf可编译的链接麻烦您帮忙看一下问题在哪里
https://cn.overleaf.com/8611865881hsqhvrkcgtmz#32dd28
main.tex里面简单的引用了一个文献，但是并没有显示出来
这是学校给出的模板，所以很多都是设定好的

**Comment by zepinglee** [comment]
> https://cn.overleaf.com/8611865881hsqhvrkcgtmz#32dd28

`natbib` 使用了 `natbib` 宏包，跟你调用的 `cite` 宏包不兼容，已经注释掉。

另外还有一处报错，跟参考文献无关。

**Comment by Mashirops** [comment]
好的，非常感谢！！
