### ISSUE TITLE
author-year格式引用中文文献，文中引用位置如何实现两个作者姓名之间连接不用and而用和

### ISSUE THREAD

**Issue by sdumyh** [zepinglee/gbt7714-bibtex-style#162]
![image](https://github.com/zepinglee/gbt7714-bibtex-style/assets/87344980/f4989ff4-c526-49b9-b617-8bf958dfdecb)

**Comment by zepinglee** [comment]
用的哪个命令？给出一段复现的代码？

**Comment by sdumyh** [comment]
https://github.com/GH1995/RUC-thesis-template-for-LaTeX
以上述项目为例，参考文献如下，在正文\cite{张2023}的地方会出现张三 and 李四，而不是张三和李四
@article{张2023,
	title = {这是题目},
	author = {张三 and 李四},
	date = {2024},
	journaltitle = {期刊},
	volume = {36},
	number = {6},
	pages = {1--10},
	issn = {1000-0000}
}

**Comment by zepinglee** [comment]
这个版本的 bst 太早了，不太好改。
