### ISSUE TITLE
如何将参考文献表改为首行缩进

### ISSUE THREAD

**Issue by HikariSakurai** [zepinglee/gbt7714-bibtex-style#168]
目前的缩进样式为悬挂缩进，是否可以通过修改文件实现首行缩进效果？

**Comment by LaoshuBaby** [comment]
两篇可能有帮助的解(cou)决(he)方案（由 @Miracle0565 提供），是从natbib的角度魔改的

* [BUCTthesis 参考文献控制在序号首行缩进](https://telegra.ph/BUCTthesis-%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%8E%A7%E5%88%B6%E5%9C%A8%E5%BA%8F%E5%8F%B7%E9%A6%96%E8%A1%8C%E7%BC%A9%E8%BF%9B-05-08)
* [BUCTthesis 中参考文献样式调整背后的原理](https://telegra.ph/BUCTthesis-%E4%B8%AD%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F%E8%B0%83%E6%95%B4%E8%83%8C%E5%90%8E%E7%9A%84%E5%8E%9F%E7%90%86-05-08)

这是因为在鄙校鄙学院的村规里面，遇到了要求参考文献首行缩进2格的参考文献排版格式（尽管总体看来悬挂缩进的占大多数，没见过我们这样的）

但是如果也有其他学校偶尔会遇到类似的要求，那上游有支持肯定是比我文中提到的这种hack cls的方法好得多

**Comment by zepinglee** [comment]
> 两篇可能有帮助的解(cou)决(he)方案（由 @Miracle0565 提供），是从natbib的角度魔改的
> 
> * [BUCTthesis 参考文献控制在序号首行缩进](https://telegra.ph/BUCTthesis-%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%8E%A7%E5%88%B6%E5%9C%A8%E5%BA%8F%E5%8F%B7%E9%A6%96%E8%A1%8C%E7%BC%A9%E8%BF%9B-05-08)
> * [BUCTthesis 中参考文献样式调整背后的原理](https://telegra.ph/BUCTthesis-%E4%B8%AD%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F%E8%B0%83%E6%95%B4%E8%83%8C%E5%90%8E%E7%9A%84%E5%8E%9F%E7%90%86-05-08)

正解。

列表的几个长度变量可以参考 enumitem 文档的图 1。

<img width="307" alt="Screenshot 2024-05-15 at 22 49 48" src="https://github.com/zepinglee/gbt7714-bibtex-style/assets/12290822/8fd7897c-918d-4023-a599-ac26c340e41e">

**Comment by HikariSakurai** [comment]
明白了，我尝试一下
