### ISSUE TITLE
编译参考文献时出现[S.1: s.n]

### ISSUE THREAD

**Issue by jianan-zhang** [zepinglee/gbt7714-bibtex-style#171]
## 编译环境
宏包版本：gbt7714 
标注样式：numbers 

## 描述问题
编译结果显示缺少项

\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
\bibliography{MIL.bib}

bib 数据库代码：
```TeX
@InProceedings{gartner2002multi,
  author    = {G{\"a}rtner, Thomas and Flach, Peter A and Kowalczyk, Adam and Smola, Alexander J},
  booktitle = {Proceedings of International Conference on Machine Learning, ICML},
  title     = {Multi-instance kernels},
  year      = {2002},
  number    = {3},
  pages     = {7},
  volume    = {2},
}
```

截图：
![微信截图_20240906120254](https://github.com/user-attachments/assets/f3a20ec7-02d0-4ab9-bb68-007beac82dd5)

**Comment by sikouhjw** [comment]
你的 texlive 版本比较老，可以下载一个新的 `gbt7714-numberical.bst`。

**Comment by jianan-zhang** [comment]
> 你的 texlive 版本比较老，可以下载一个新的 。`gbt7714-numberical.bst`

感谢，按照您的建议问题已经解决了
