### ISSUE TITLE
如何删除文献列表中的OL标志

### ISSUE THREAD

**Issue by ChenBaiyang** [zepinglee/gbt7714-bibtex-style#173]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：square, numbers, super, sort&compress

## 描述问题
在带有DOI的文献记录中，无论是什么类型的文献，在Reference列表中都会自动识别为 OL，例如：

[1] KNORR E M, NG R T, TUCAKOV V. Distance-based outliers: algorithms and applications[J/OL]. The VLDB Journal, 2000, 8(3): 237-253. DOI: 10.1007/s007780050006.

上述问题，除了手动删除bib数据库中的DOI字段以外，还有其他解决方法吗？

**Comment by zepinglee** [comment]
> 在带有DOI的文献记录中，无论是什么类型的文献，在Reference列表中都会自动识别为 OL

国标要求的。

> 上述问题，除了手动删除bib数据库中的DOI字段以外，还有其他解决方法吗？

将对应 .bst 文件的这里改为 `#0`。

**Comment by ChenBaiyang** [comment]
非常感谢，解决了
