### ISSUE TITLE
作者考虑过将这个package上传到CTAN上吗？

### ISSUE THREAD

**Issue by GoBigorGoHome** [zepinglee/gbt7714-bibtex-style#18]
如题。

**Comment by zepinglee** [comment]
接口还没完全定下来，而且宏包使用说明也没写完，暂时不放吧

**Comment by zepinglee** [comment]
而且，各个学校基本都要在标准的基础上再改一改，很少用原标准的，所以我感觉上传到 CTAN 意义不大

**Comment by GitatHub** [comment]
你这个不是国标嘛，又不是学校论文规范。可以作为 GBT 上传到 CTAN ？

**Comment by leo-liu** [comment]
有个标准的上传意义还是挺大的，bst 这块儿少有面向中文的。当然可能新一点的作者都去写 biblatex 了，那边排序容易一些。

**Comment by liubenyuan** [comment]
不过，现在这个包我使用的时候就是放在目录下。。。

**Comment by leo-liu** [comment]
自用都是这样的。发到 CTAN 的理由主要是为了方便给别人用，TeX 发行版会安装需要的宏包、文档。

2018-04-02 17:04 GMT+08:00 liubenyuan <notifications@github.com>:

**Comment by leo-liu** [comment]
可喜可贺，估计能赶上进 TL18。
https://ctan.org/pkg/gbt7714
