### ISSUE TITLE
隐式的显示参考文献跳转

### ISSUE THREAD

**Issue by qiuzhu** [zepinglee/gbt7714-bibtex-style#19]
- 最近发现，一些期刊杂志对于参考文献的跳转处理，几乎都是采用隐藏的方式跳转到文章的出去，这样在电子版上更有利于阅读和检索，相同的问题，在texexhange中有人提出相似的问题，看了下answer，需要修改bst文件，连接如下 https://tex.stackexchange.com/a/64695/117534

**Comment by zepinglee** [comment]
就你的了解，链接是更多加在 title 上还是 journal number volume papges 上？

**Comment by qiuzhu** [comment]
@zepinglee 两种情况都有，要是加在title上，应该更容易实现，加在期刊号或者期刊名字上，也见过，elsveier上现在都是加在title上，pysic of view是加在期刊名字上，arxaiv啥的貌似也是加在期刊名字上

_Sent from my HUAWEI EVA-DL00 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zepinglee** [comment]
已经添加
