### ISSUE TITLE
著者-年制的文献列表中作者部分结束的标点似乎不正确

### ISSUE THREAD

**Issue by wnduan** [zepinglee/gbt7714-bibtex-style#20]
使用您这里的两个 .bst 文件配合 natbib 做了一个简单测试，采用 gbt-7714-2015-numerical 顺序编码时得到的结果是符合规范要求的：

<img width="450" alt="2017-08-30 05 39 41" src="https://user-images.githubusercontent.com/6158539/29845526-c0111fda-8d45-11e7-9721-a6fd08d2cf73.png">

但是同样设置，改用著者-年制的 gbt-7714-2015-author-year 时结果是：

<img width="450" alt="2017-08-30 05 42 41" src="https://user-images.githubusercontent.com/6158539/29845621-2e409be8-8d46-11e7-9c8c-0897c7e557ad.png">

看起来似乎是作者部分最后结尾的标点没有正确处理。

**Comment by zepinglee** [comment]
请仔细阅读 GB/T 7714-2015 第 9.2 节：
<img width="855" alt="screen shot 2017-08-30 at 10 02 45 am" src="https://user-images.githubusercontent.com/12290822/29852053-673a970e-8d6a-11e7-932f-854a43e10136.png">

**Comment by wnduan** [comment]
感谢您的及时回复. 没搞清情况就提 Issue 了，真不好意思. 以往都是用顺序编码的，没有怎么注意著者-年的要求. 看来还是要好好学习一下规范.
