### ISSUE TITLE
windows用户想知道如何使用这个style

### ISSUE THREAD

**Issue by shixuguo** [zepinglee/gbt7714-bibtex-style#22]
看到了makefile但是用不了啊

**Comment by zepinglee** [comment]
把 sty 文件和 bst 文件 copy 到你的 main.tex 同一目录下，然后可以按照 test/main.tex 去用了

**Comment by shixuguo** [comment]
可以用了。

作为windows用户，我找到了matlab里的一个gmake.exe
用这个可以使用makefile了。

但是你的makefile文件里有一些命令不支持。
因此，我没有办法用gmake去安装
只能用gmake去测试test文件夹内的makefile

**Comment by Stone-Zeng** [comment]
@zepinglee 其实可以试试 lua 脚本的。LaTeX3 team 弄了个 `l3build`，在 LaTeX2e 下面也能用。基本上 luatex 都会装，所以跨平台这个问题就可以解决了。

**Comment by zepinglee** [comment]
这个 gmake 太不主流了吧，gnu make 应该也有 windows 版。

我的 Makefile 是自己做测试时方便，比如把 全部 bbl concatenate 起来 diff 。

你自己编译 latex 的话可以用 latexmk，比写 makefile 方便

**Comment by zepinglee** [comment]
好像 ctex-kit 是用 l3build 搞的吧？

**Comment by zepinglee** [comment]
@Stone-Zeng 不错，看来你对 LaTeX3 最新的东西很了解啊……我觉得可以试试 l3build

我现在全都用 mac，所以基本不怎么考虑在 windows 下开发的问题。

**Comment by zepinglee** [comment]
@Stone-Zeng 我稍微试了一下 l3build，但是发现几个问题：
1. l3build 的测试文件似乎只能对比输出到 log 的内容，没法对比生成的 bbl 文件（跟一个标准的 bbl）
2. texlua build.lua check 的时候不会调用 bibtex
3. texlua build.lua install 没法处理 bst 文件
所以，我觉得目前 l3build 只是用于打包比较方便，但是对于单元测试就很不方便。想请教下你是怎么用的？

**Comment by nanmu42** [comment]
@shixuguo 可以用Bash on Windows(WSL)，打通Linux这边的支持。

**Comment by Stone-Zeng** [comment]
@zepinglee  我还没用过 l3build 来着……等我这几天考完试回来研究一下 😭

**Comment by Stone-Zeng** [comment]
另外 @nanmu42 用 bash on windows 的话这个子系统里面也要装 texlive，不好直接用 windows 里面的吧

**Comment by nanmu42** [comment]
是的，要装Linux版本的TeX Live或者MiKTeX.

如果觉得麻烦的话也可以试试[Docker镜像](https://hub.docker.com/r/nanmu42/tex-package-test-bench/)……

**Comment by shixuguo** [comment]
@nanmu42  能够详细说说么？如何在子系统里安装texlive 或者有没有推荐解说比较详细的文章

**Comment by nanmu42** [comment]
Win10打开PowerShell，输入后回车：
```powershell
bash
```

子系统基本上是一个Ubuntu，按Ubuntu的安装方式来就好。
