### ISSUE TITLE
有没有可能按出现的顺序显示参考文献标注

### ISSUE THREAD

**Issue by GitatHub** [zepinglee/gbt7714-bibtex-style#23]
这里说的不是参考文献列表中的顺序，而是指正文里参考文献标注出现的顺序。
具体描述和这个类似：
https://tex.stackexchange.com/questions/61877/natbib-sorting-and-citation-order-by-appearance 
目前我遇到的情况是默认按作者的首字母排序，比如
我手动设置顺序 \citep{mac1986,kill2009}，希望的结果是 (Mac et al., 1986; Kill et al., 2009)，
而默认输出的结果是 (Kill et al., 2009; Mac et al., 1986)。
有没有参数可以修改？

**Comment by zepinglee** [comment]
这个问题主要是因为调用 `natbib` 的时候带了 `sort&compress` 参数，去掉这个参数后则可以得到你要的效果。

我会在下个版本中修复 author-year 模式的这个问题。

**Comment by zepinglee** [comment]
Fixed in 9429fba.

**Comment by GitatHub** [comment]
谢谢。不过似乎更新了之后还是不能按出现顺序排序。
是这么用的
\usepackage[authoryear]{gbt7714}
...
中文内容
\citep{mac1986,kill2009}
中文内容
...

>xelatex main
> bibtex main
This is BibTeX, Version 0.99d (TeX Live 2017/W32TeX)
The top-level auxiliary file: main.aux
The style file: gbt7714-plain.bst
Database file #1: references.bib

>xelatex main
>xelatex main

结果出来还是 (Kill et al., 2009; Mac et al., 1986)

**Comment by zepinglee** [comment]
我这里测试没问题，看看不是文件没有更新？

**Comment by GitatHub** [comment]
谢谢回复。
是我使用的模板自身也有问题，已经解决。
耽误您时间了。非常感谢。
