### ISSUE TITLE
论文集中的文章，如果要改成in:而不是//，怎么改

### ISSUE THREAD

**Issue by bdgong** [zepinglee/gbt7714-bibtex-style#27]
如题，纯粹是为了符合学校要求

**Comment by zepinglee** [comment]
这样改 https://github.com/zepinglee/gbt7714-bibtex-style/commit/354ebcd36dd9fa614075d2dd912cb039d775546f

**Comment by zepinglee** [comment]
可能需要考虑下中文文献

**Comment by bdgong** [comment]
目前只有英文文献，完美解决。谢谢

**Comment by lynzrand** [comment]
> 
> 
> 这样改 [zepinglee/gbt7714-bibtex-style@354ebcd](https://github.com/zepinglee/gbt7714-bibtex-style/commit/354ebcd36dd9fa614075d2dd912cb039d775546f)

您好，这个链接已经失效了，可以在重新发布一下修改方式吗？

**Comment by zepinglee** [comment]
> > 这样改 [zepinglee/gbt7714-bibtex-style@354ebcd](https://github.com/zepinglee/gbt7714-bibtex-style/commit/354ebcd36dd9fa614075d2dd912cb039d775546f)
> 
> 您好，这个链接已经失效了，可以在重新发布一下修改方式吗？

那个方法已经过时，最新的是
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/be1161346a273549b2929e4fb6204e8679378603/gbt7714-numerical.bst#L70-L71
分别改成 `#0` 和 `#1`。

**Comment by lynzrand** [comment]
> 
> 
> > > 这样改 [zepinglee/gbt7714-bibtex-style@354ebcd](https://github.com/zepinglee/gbt7714-bibtex-style/commit/354ebcd36dd9fa614075d2dd912cb039d775546f)
> > 
> > 
> > 您好，这个链接已经失效了，可以在重新发布一下修改方式吗？
> 
> 那个方法已经过时，最新的是
> 
> https://github.com/CTeX-org/gbt7714-bibtex-style/blob/be1161346a273549b2929e4fb6204e8679378603/gbt7714-numerical.bst#L70-L71
> 
> 分别改成 `#0` 和 `#1`。

谢谢！

**Comment by AlexaraWu** [comment]
修改这两个参数后，对于存在编者姓名的的文献，“In:” 出现在编者姓名与论文集标题的中间。是不是把 “In:” 放在编者姓名之前更为妥当？

Entry:
```bibtex
@incollection{TestKey,
    author       = {Joe Bloggs},  
    title        = {The Interesting Chapter Title},
    chapter      = {9},
    pages        = {100--207},
    booktitle    = {The Best Book Title},
    editor       = {John Mann and Peter Person},
    publisher    = {Cambridge University Press},
    year         = {1997},
}
```

Output:
```latex
\bibitem[Bloggs(1997)]{TestKey}
BLOGGS J.
\newblock The interesting chapter title\allowbreak[M].
\newblock MANN J, PERSON P.
\newblock In: The Best Book Title.
\newblock Cambridge University Press, 1997: 100-207.
```

**Comment by zepinglee** [comment]
> 修改这两个参数后，对于存在编者姓名的的文献，“In:” 出现在编者姓名与论文集标题的中间。是不是把 “In:” 放在编者姓名之前更为妥当？

有道理，我稍后修改一下。

**Comment by zepinglee** [comment]
> 修改这两个参数后，对于存在编者姓名的的文献，“In:” 出现在编者姓名与论文集标题的中间。是不是把 “In:” 放在编者姓名之前更为妥当？

@AlexaraWu 已在 5b6cb55 中修改。
