### ISSUE TITLE
中文学位论文会出现[出版地不详]

### ISSUE THREAD

**Issue by TokyoClod** [zepinglee/gbt7714-bibtex-style#29]
bibtex代码为：
```
@phdthesis{吴妍2017,
	type = {硕士},
	title = {单目视觉下基于合作目标的无人机定位定姿问题研究},
	language = {中文;},
	school = {南京理工大学},
	author = {吴, 妍},
	year = {2017},
	keywords = {特征匹配, UAV, Pose estimation, 无人机, 合作目标, 畸变校正, 扩展卡尔曼滤波, 位姿估计, Cooperative target, Distortion correction, Extended Kalman filtering, Feature matching}
}
```
结果为：
```
吴妍.单目视觉下基于合作目标的无人机定位定姿问题研究[D]. [出版地不详]:南京理工大学, 2017.
```
按照知网导出的参考文献格式来看，学位论文应该后面直接加学校，不需要出版社了，希望可以改进，谢谢！

**Comment by zepinglee** [comment]
![screen shot 2018-05-29 at 10 14 05 am](https://user-images.githubusercontent.com/12290822/40634718-14bb8462-6329-11e8-8f9f-2928ce1f7c0a.png)

https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf

**Comment by zepinglee** [comment]
我正在加一些可以方便定制的选项，稍后会 commit 上去

**Comment by TokyoClod** [comment]
好的，辛苦啦[抱拳]！

**Comment by zepinglee** [comment]
你试一下 f7bed34 ，只需要将这里 https://github.com/zepinglee/gbt7714-bibtex-style/blob/f7bed34df24b03934a3fecc034d845455c29f56c/gbt7714.dtx#L541 改成 `#0` 就不再出现“出版地不详”了

**Comment by TokyoClod** [comment]
@zepinglee 不好意思，这才收到邮件提醒。
看到您的修改了，可是这个要怎么用呢？我是把 bst 文件和 sty 文件复制到我的工作目录，用的xelatex编译的，请问要怎样使用您提示的这个选项呢？

**Comment by zepinglee** [comment]
修改 bst 文件中的前面几行

**Comment by CSGrandeur** [comment]
> 修改 bst 文件中的前面几行

我把`'show.missing.address.publisher :=`前面改成 #0 了，[S.l: s.n.]依然在

**Comment by zepinglee** [comment]
@CSGrandeur 给个 bib 例子？

**Comment by CSGrandeur** [comment]
这个规则确实挺闹心的。毕竟很多会议的官方网站提供的bib都是不全的，地址都得手填`@_@`
---

cls里：
```
\RequirePackage[numbers,2005]{gbt7714}
```
```
@InProceedings{Schmidhuber1991possibility,
  author    = {Schmidhuber, J{\"u}rgen},
  title     = {A possibility for implementing curiosity and boredom in model-building neural controllers},
  booktitle = {Proc. of the international conference on simulation of adaptive behavior: From animals to animats},
  year      = {1991},
  pages     = {222--227},
}
@InProceedings{Pathak2016Context,
  author    = {Pathak, Deepak and Krahenbuhl, Philipp and Donahue, Jeff and Darrell, Trevor and Efros, Alexei A.},
  title     = {Context Encoders: Feature Learning by Inpainting},
  booktitle = {The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)},
  year      = {2016},
  month     = {June},
}
@InProceedings{Maas2013Rectifier,
  author    = {Maas, Andrew L and Hannun, Awni Y and Ng, Andrew Y},
  title     = {Rectifier nonlinearities improve neural network acoustic models},
  booktitle = {Proc. icml},
  year      = {2013},
  volume    = {30},
  number    = {1},
  pages     = {3},
}
@InProceedings{Portilla2001Adaptive,
  author    = {J. {Portilla} and V. {Strela} and M. J. {Wainwright} and E. P. {Simoncelli}},
  title     = {Adaptive Wiener denoising using a Gaussian scale mixture model in the wavelet domain},
  booktitle = {Proceedings 2001 International Conference on Image Processing (Cat. No.01CH37205)},
  year      = {2001},
  volume    = {2},
  month     = {Oct},
  pages     = {37-40 vol.2},
  doi       = {10.1109/ICIP.2001.958418},
  keywords  = {Gaussian noise;wavelet transforms;interference suppression;maximum likelihood estimation;image restoration;covariance analysis;image representation;adaptive Wiener denoising;Gaussian scale mixture model;wavelet domain;statistical model;image decomposition;overcomplete wavelet pyramid;Gaussian random field;log-normal prior;additive Gaussian noise;MAP estimate;multiplier variable;Wiener estimator;image restoration;image representation;Noise reduction;Wavelet domain;Humans;Band pass filters;Additive noise;Gaussian noise;White noise;Data mining;Image restoration;Probability},
}
```

![image](https://user-images.githubusercontent.com/5326601/56147639-3ef17980-5fdb-11e9-9405-85f3a2fa071b.png)
![image](https://user-images.githubusercontent.com/5326601/56147668-4b75d200-5fdb-11e9-93d3-81199cf9e973.png)

**Comment by zepinglee** [comment]
@CSGrandeur 无法复现你的问题

![Screen Shot 2019-04-16 at 9 19 51 AM](https://user-images.githubusercontent.com/12290822/56175227-cca78600-6028-11e9-8985-9602112daea3.png)

**Comment by CSGrandeur** [comment]
不会吧。。。

确认一下，用的现在仓库里的release v1.1.1的`gbt7714.sty`和`gbt7714-unsrt.bst`，在cls文件里是`\RequirePackage[numbers,2005]{gbt7714}`

`gbt7714-unsrt.bst`的51行`#1`改成了`#0`：` #0 'show.missing.address.publisher :=`

我重新用仓库的`gbt7714.sty`和`gbt7714-unsrt.bst`替换了一次本地的，并改了`#0`那行，也检查了只有`\RequirePackage[numbers,2005]{gbt7714}`一句引入bib样式的语句。

是还有什么我可能疏忽的地方吗？

**Comment by CSGrandeur** [comment]
![image](https://user-images.githubusercontent.com/5326601/56232897-66684500-60b4-11e9-9e40-ab2e2dad89bf.png)
![image](https://user-images.githubusercontent.com/5326601/56232911-6e27e980-60b4-11e9-9e18-de93497d4607.png)

链接：https://pan.baidu.com/s/1oQLlrS0Ri4YGeLYK_QzRKA 
提取码：5zy7 

xelatex编译的

**Comment by zepinglee** [comment]
@CSGrandeur 你需要用 https://github.com/CTeX-org/gbt7714-bibtex-style/tree/master/versions/2005 这个版本的，我前不久改了一下目录，忘记在 readme 里说这个了

**Comment by CSGrandeur** [comment]
原来如此。。我就说怎么-2005那个文件没有了，还以为合并了那么方便。
