### ISSUE TITLE
讨论 GB 7714-87 的具体事项

### ISSUE THREAD

**Issue by sikouhjw** [zepinglee/gbt7714-bibtex-style#84]
现在遇到的问题是 GB 7714-87 要求的部分著录项目是 GB/T 7714-2015 所没有的，讨论该取什么名字来表示

**Comment by sikouhjw** [comment]
我对参考文献不是太了解，有些没法对应上（有些确实是没有），麻烦大家补充一下（
# 专著
- 主要责任者 = `author`
- 书名 = `title`
- 文献类型标识（供选择）= `mark`
- 其他责任者（供选择）
- 版本 = `edition`
- 出版项（出版地：出版者，出版年）= `address, publisher, year`
- 文献数量（供选择）
- 丛编项（供选择）
- 附注项（供选择）
- 文献标准编号（供选择）
# 连续出版物
- 题名 = `title`
- 主要责任者 = `author`
- 版本 = `edition`
- 卷、期、年、月或其他标识〔年．月，卷（期）～年．月，卷（期）．〕（供选择）= `volume, number, year, month`（这个还得要起始跟终点两个）
- 出版项（出版地：出版者，出版年）= `address, publisher, year`
- 丛编项（供选择）
- 附注项（供选择）
- 文献标准编号（供选择）
# 专利文献
- 专利申请者 = `author`
- 专利提名 = `title`
- 其他责任者（供选择）
- 附注项（供选择）
- 文献标识符
- 专利国别
- 专利文献种类
- 专利号 = `number`
- 出版日期 = `date`
# 专著中析出的文献
- 析出责任者 = `author`
- 析出题名 = `title`
- 析出其他责任者（供选择）
- 原文献责任者
- 原文献题名
- 版本 = `edition`
- 出版项（出版地：出版者，出版年）= `address, publisher, year`
- 在原文献中的位置（原文先的年代顺序号、卷、期、部分号、页数）
# 连续出版物中析出的文献
- 析出责任者 = `author`
- 析出题名 = `title`
- 析出其他责任者（供选择）
- 原文献题名
- 版本 = `edition`
- 在原文献中的位置

**Comment by zepinglee** [comment]
文献类型和著录项目基本按照 [`btxdoc`](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf) 的格式，如果 bibtex 没有的再按照 [`biblatex`](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) 的格式。

- 文献类型标识不必填
- 原文献题名 `booktitle` 或 `journal`
- 在原文献中的位置 `volume`, `number`, `pages`

其他的先不必填，留给我处理。
