### ISSUE TITLE
对于特殊的电子资源（比如github上的项目以及arxiv上的论文等）的按照国标如何引用？

### ISSUE THREAD

**Issue by fu123456** [zepinglee/gbt7714-bibtex-style#89]
现在特别是计算机学科很多的论文都是上传到arxiv上在线发表，导致在论文中需要引用上面的一些论文，但是arxiv网站以及dblp网站提供了bib文件，但是这些文件貌似不符合咱们的国标，比如下面的一个arxiv上的论文，arxiv网站提供的bib文件如下：
```tex
@misc{lettry2018unsupervised,
      title={Unsupervised Deep Single-Image Intrinsic Decomposition using Illumination-Varying Image Sequences}, 
      author={Louis Lettry and Kenneth Vanhoey and Luc van Gool},
      year={2018},
      eprint={1803.00805},
      archivePrefix={arXiv},
      primaryClass={cs.CV}
}
```
arxiv网上还提供了dblp的链接，提供了另外一种bib如下：
```tex
@article{DBLP:journals/corr/abs-1803-00805,
  author    = {Louis Lettry and
               Kenneth Vanhoey and
               Luc Van Gool},
  title     = {Deep Unsupervised Intrinsic Image Decomposition by Siamese Training},
  journal   = {CoRR},
  volume    = {abs/1803.00805},
  year      = {2018},
  url       = {http://arxiv.org/abs/1803.00805},
  eprinttype = {arXiv},
  eprint    = {1803.00805},
  timestamp = {Mon, 13 Aug 2018 16:48:44 +0200},
  biburl    = {https://dblp.org/rec/journals/corr/abs-1803-00805.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
```
另外，通过google scholar搜索，有下面的bib格式：
```tex
@article{lettry2018deep,
  title={Deep unsupervised intrinsic image decomposition by siamese training},
  author={Lettry, Louis and Vanhoey, Kenneth and Van Gool, Luc},
  journal={arXiv preprint arXiv:1803.00805},
  year={2018}
}

```
也就是说同一个资源（论文），上面提供了三个不同的bib文件。
那么这个时候这个arxiv上的论文按照国标应该如何弄比较合理呢。因为这些电子资源和我们普通的网页又不一样，具有一定的特殊性。

**Comment by GabrielLin** [comment]
请问按照最新的修改版本，arXiv的预印本，同时需要显示文章编号的话，bib文件应该怎么写？谢谢。

**Comment by zepinglee** [comment]
> 请问按照最新的修改版本，arXiv的预印本，同时需要显示文章编号的话，bib文件应该怎么写？谢谢。

按照 biblatex 的要求的格式就可以：

@preprint{lettry2018unsupervised,
  title         = {Unsupervised Deep Single-Image Intrinsic Decomposition using Illumination-Varying Image Sequences},
  author        = {Louis Lettry and Kenneth Vanhoey and Luc van Gool},
  year          = {2018},
  eprint        = {1803.00805},
  archivePrefix = {arXiv},
  url           = {https://arxiv.org/abs/1803.00805},
}

**Comment by GabrielLin** [comment]
> > 请问按照最新的修改版本，arXiv的预印本，同时需要显示文章编号的话，bib文件应该怎么写？谢谢。
> 
> 按照 biblatex 的要求的格式就可以：
> 
> ```
> @preprint{lettry2018unsupervised,
>   title         = {Unsupervised Deep Single-Image Intrinsic Decomposition using Illumination-Varying Image Sequences},
>   author        = {Louis Lettry and Kenneth Vanhoey and Luc van Gool},
>   year          = {2018},
>   eprint        = {1803.00805},
>   archivePrefix = {arXiv},
>   url           = {https://arxiv.org/abs/1803.00805},
> }
> ```

谢谢您。

**Comment by yc-guo19** [comment]
请问如果本科生的书面翻译希望翻译一篇arXiv的话，文章号出不来怎么办？
<img width="710" alt="image" src="https://user-images.githubusercontent.com/88889094/216629343-41114d7e-a1cd-48f1-9b68-c9e4b1a15b14.png">
正文的参考文献是正常的，可以显示arXiv文章号。

**Comment by yc-guo19** [comment]
已通过奇怪的方法解决：从正文的bbl里面复制了这一条并且手动做了一个bbl文件
