### ISSUE TITLE
online类型文献过多报错

### ISSUE THREAD

**Issue by CuiiGen** [zepinglee/gbt7714-bibtex-style#90]
![Snipaste_2021-11-01_19-33-35](https://user-images.githubusercontent.com/46126598/139665482-38b1b0ec-4f2d-471e-893e-4af4a910653d.png)

**Comment by CuiiGen** [comment]
其它online类型文献没有问题，总之报错原因莫名其妙

**Comment by zepinglee** [comment]
大括号没配齐，给下原始 `.bib` 数据方便我测试。

**Comment by CuiiGen** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zepinglee/gbt7714-bibtex-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 晚上7:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zepinglee/gbt7714-bibtex-style] online类型文献过多报错 (Issue #90)





 
大括号没配齐，给下原始 .bib 数据方便我测试。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
> 
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zepinglee/gbt7714-bibtex-style" ***@***.***&gt;; 发送时间:&nbsp;2021年11月1日(星期一) 晚上7:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zepinglee/gbt7714-bibtex-style] online类型文献过多报错 (Issue #90) 大括号没配齐，给下原始 .bib 数据方便我测试。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你回复了个啥？

**Comment by CuiiGen** [comment]
[refs_ch9.txt](https://github.com/zepinglee/gbt7714-bibtex-style/files/7453689/refs_ch9.txt)

**Comment by zepinglee** [comment]
大概是因为，你的 .bib 中很多文献缺失年份，bst 处理时会自动加上字母 `a`（ASCII 值 97）, `b`, `c`……但是需要的字母太多了，结果数到了  128 时不能转成合法的 ASCII 字符就报错了。

**Comment by CuiiGen** [comment]
> 大概是因为，你的 .bib 中很多文献缺失年份，bst 处理时会自动加上字母 `a`（ASCII 值 97）, `b`, `c`……但是需要的字母太多了，结果数到了 128 时不能转成合法的 ASCII 字符就报错了。

我发现加了`urldate`也是会报错，能修改一下这个么，毕竟`year`在`numerical`类型中也不是必要的

**Comment by CuiiGen** [comment]
@zepinglee 你好请问一下这个问题为修正吗？还是`online`类型的参考文献也必须要加`year`？

**Comment by zepinglee** [comment]
> 我发现加了`urldate`也是会报错，能修改一下这个么，毕竟`year`在`numerical`类型中也不是必要的

urldate 是引用日期，不是发表的日期。需要 year 主要是因为 `natbib` 有 `\citeauthor` 和 `\citeyear` 这些功能。

> @zepinglee 你好请问一下这个问题会修正吗？还是`online`类型的参考文献也必须要加`year`？

我这两天修一下这个问题。
