### ISSUE TITLE
图片在文章内容之后，caption中引用的序号却从1开始

### ISSUE THREAD

**Issue by mythmyp** [zepinglee/gbt7714-bibtex-style#91]
## 编译环境
宏包版本：gbt7714 v2.1.2
标注样式：numbers

## 描述问题
我的图片放在一段之后，图片caption中有引用的文章，但是序号却从1开始，第一段中的序号接在其后

**Comment by zepinglee** [comment]
可以用 `notoccite` 宏包解决这个问题。
