### ISSUE TITLE
author-year格式下，参考文献列表加编号的问题

### ISSUE THREAD

**Issue by walkeatround** [zepinglee/gbt7714-bibtex-style#92]
老师您好，我在使用author-year格式引用文献时，在文献列表中默认好像是没有自动显示编号的，请问需要修改何处来实现自动编号呢？谢谢老师指点！
希望实现的效果如下：
![image](https://user-images.githubusercontent.com/36181971/144758293-7cd9facf-4ef5-40b8-9630-c10216854639.png)

**Comment by zepinglee** [comment]
国标就是这样要求的。
<img width="735" alt="Screen Shot 2021-12-06 at 10 57 30" src="https://user-images.githubusercontent.com/12290822/144779914-f9b133df-1883-441d-9b3b-a8fa635bc73d.png">

如果实在需要编号，可以在 `\bibliography` 前设置 `\citestyle{super}`

**Comment by walkeatround** [comment]
> 国标就是这样要求的。 <img alt="Screen Shot 2021-12-06 at 10 57 30" width="735" src="https://user-images.githubusercontent.com/12290822/144779914-f9b133df-1883-441d-9b3b-a8fa635bc73d.png">
> 
> 如果实在需要编号，可以在 `\bibliography` 前设置 `\citestyle{super}`

明白了，非常感谢老师解答！这个格式主要是我们学校如此要求的，我也不太明白为什么会要求这样😂😂可能为了方便看我们引用的文献数量吧
