### ISSUE TITLE
如何得到不是上标的引用标记

### ISSUE THREAD

**Issue by nkuwenjian** [zepinglee/gbt7714-bibtex-style#94]
您好，

非常感谢您的模板。想请问一个小问题，我用\cite{}之后，得到的全都是如下所示的上标引用标记，是否有命令可以得到常规引用标记，而不是上标。非常感谢您的回复！

![screenshot](https://user-images.githubusercontent.com/22639682/155729668-edb470fd-d8b3-4289-b464-d6add98df2c9.png)

**Comment by sikouhjw** [comment]
1. `texdoc gbt7714`
2. 这是宏包，不是模板

**Comment by zepinglee** [comment]
`\citestyle{numbers}` 可以切换为与正文平排的样式。感觉文档中写得不是很详细，我再补充一些吧。

**Comment by nkuwenjian** [comment]
非常感谢您的回复，按照您的建议现在可以切换为正文平排的样式了。

还有一个小问题，可能是和我的模板以及您的gbt7714.sty相关的，就是我引用之后，目录出现这样的错误

![screenshot](https://user-images.githubusercontent.com/22639682/155737551-529f477f-9f4c-4ec8-8e2d-c090a1d3a594.png)

我的编译环境是texlive 2011，模板比较老了，不知道是不是和您的这个sty文件有些冲突。

不知道您之前是否遇到过这样的问题，或者有其他人反映过类似的问题。

非常感谢您的回复。

**Comment by sikouhjw** [comment]
texlive 2011……太老了，你把跟参考文献有关的部分打包（包含 tex 必要的内容、cls、bib）发上来吧。

**Comment by zepinglee** [comment]
> 非常感谢您的回复，按照您的建议现在可以切换为正文平排的样式了。
> 
> 还有一个小问题，可能是和我的模板以及您的gbt7714.sty相关的，就是我引用之后，目录出现这样的错误
> 
> ![screenshot](https://user-images.githubusercontent.com/22639682/155737551-529f477f-9f4c-4ec8-8e2d-c090a1d3a594.png)
> 
> 我的编译环境是texlive 2011，模板比较老了，不知道是不是和您的这个sty文件有些冲突。
> 
> 不知道您之前是否遇到过这样的问题，或者有其他人反映过类似的问题。
> 
> 非常感谢您的回复。

发一下模板的链接？我去瞧瞧

**Comment by nkuwenjian** [comment]
您好，我已经把整个包放到github上了，连接 https://github.com/nkuwenjian/thesis，现在是用xelatex+bibtex编译通过。

这个模板挺老的，我之前用texlive 2015/2019/2020试过，编译出来的目录都有问题（正确目录是第二章而不是第2章，但用高版本texlive编译得到的是阿拉伯数字），后来降到2011版本就正常了（有一个manual上面写的系统要求是ctex 2.9或者texlive 2011以后版本，2012到2014这几个版本我没试过）

非常感谢！

**Comment by zepinglee** [comment]
<img width="678" alt="Screen Shot 2022-02-25 at 23 58 59" src="https://user-images.githubusercontent.com/12290822/155746779-e0cf5f78-ebda-42f2-97d1-8fb8240f03f8.png">

我这里编译出来的没有这个问题。

不过我搜到了 <https://github.com/NewFuture/NKThesis> 项目，建议不要这个旧模板了。

**Comment by nkuwenjian** [comment]
请问您的编译环境是哪个版本，非常感谢！

**Comment by zepinglee** [comment]
> 请问您的编译环境是哪个版本，非常感谢！

TeX Live 2021, macOS

**Comment by sikouhjw** [comment]
> 好的，感谢！还有您是用xelatex编译的么？还是pdflatex

texlive 2021 + win 10 + `pdflatex`，没有你说的问题。

**Comment by zepinglee** [comment]
我改了许多才编译通过。
