### ISSUE TITLE
如何隐藏 "参考文献" 标题?

### ISSUE THREAD

**Issue by MichaelWei7** [zepinglee/gbt7714-bibtex-style#96]
使用命令 `\bibliography{bibfile}` 会自动生成参考文献, 但同时也会产生 "参考文献" 标题. 为了能够在目录中得到索引, 我又不得不加上 `\section{参考文献}`, 但这样就会产生两个 "参考文献" 标题, 如下图所示:
![image](https://user-images.githubusercontent.com/44831985/159154192-9cf3049c-1f16-4cfe-aae4-8ab63084aa87.png)
请问有什么办法可以隐藏 \bibliography 自动生成的标题? 谢谢!

**Comment by sikouhjw** [comment]
建议不要手动生成“参考文献”标题，而是修改 `\bibsection`。
```tex
\documentclass{ctexart}
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
\renewcommand\bibsection{\section{参考文献}}
\begin{document}
  test
  \nocite{*}
  \bibliography{xampl-zh.bib}
\end{document}
```

**Comment by MichaelWei7** [comment]
感谢, 解决了我的问题!

**Comment by zepinglee** [comment]
@sikouhjw 感谢帮忙回复！

@MichaelWei7 `\bibsection` 是 `natbib` 的接口。
