### ISSUE TITLE
et al设置对第一个文献不起作用

### ISSUE THREAD

**Issue by Juelianqvq** [zepinglee/gbt7714-bibtex-style#97]
bibtex下bst配置(或许是我的配置哪里有误？)
  #2 'citation.et.al.min :=
  #1 'citation.et.al.use.first :=
  #4 'bibliography.et.al.min :=
  #10 'bibliography.et.al.use.first :=
![屏幕截图 2022-03-26 132211](https://user-images.githubusercontent.com/42963620/160225992-5afe7965-c367-4de0-a4a5-062659534de4.png)
以及会出现空格太大的情形
![屏幕截图 2022-03-26 132424](https://user-images.githubusercontent.com/42963620/160226076-724911c5-9504-4e8b-9f09-23b04f041124.png)
在author-year与gbt7714-2005都出现了上述两个格式不太统一的情况，请问作者大大要怎么修正呢？

**Comment by Juelianqvq** [comment]
只有第一个被引用的文献会出现et.al 设置不起作用，也就是说如果我把第一个文献去了，那第二个文献就会出现et.al了

**Comment by zepinglee** [comment]
把 bib 贴过来让我测试一下？

**Comment by Juelianqvq** [comment]
[Uploading test.txt…]()

**Comment by Juelianqvq** [comment]
[test.txt](https://github.com/zepinglee/gbt7714-bibtex-style/files/8354746/test.txt)

**Comment by Juelianqvq** [comment]
不好意思 et al的问题解决了 是因为bib里写的就是others 那空格间距比较大这一点有什么方法处理吗...

**Comment by sikouhjw** [comment]
空格太大是因为 latex 本身的特性，句号『.』被当成一段话的结尾，间距比普通空格长度大一点。

建议别纠结。

**Comment by Juelianqvq** [comment]
> 空格太大是因为 latex 本身的特性，句号『.』被当成一段话的结尾，间距比普通空格长度大一点。
> 
> 建议别纠结。

**Comment by zepinglee** [comment]
> 不好意思 et al的问题解决了 是因为bib里写的就是others 那空格间距比较大这一点有什么方法处理吗...

```
#4 'bibliography.et.al.min :=
#10 'bibliography.et.al.use.first :=
```
的含义是作者数量达到 4 个或 4 个以上时，使用前 10 个并加“et al”。你确认一下没有搞错。

bibtex 是按照 `.bbl` 的内容输出的：
```tex
\bibitem[Peng et~al.(2019)Peng, Wu, Chen, and Huang]{peng2019collaborative}
PENG H, WU J, CHEN S, et~al.
\newblock Collaborative channel pruning for deep
  networks\allowbreak[C]//\allowbreak
International Conference on Machine Learning.
\newblock PMLR, 2019: 5113-5122.
```
`\newblock` 的定义是 `\newcommand\newblock{\hskip .11em\@plus.33em\@minus.07em}`，这是 LaTeX 和 BibTeX 的习惯，为了更方便地断行和阅读。
