### ISSUE TITLE
询问：是否存在接口，使能在默认的顺序编码制下将\citet的et al.替换成中文的“等”？

### ISSUE THREAD

**Issue by GreenieQwQ** [zepinglee/gbt7714-bibtex-style#99]
是否存在接口，使能在默认的顺序编码制下将\citet的et al.替换成中文的“等”？

**Comment by zepinglee** [comment]
并没有。目前仅有一个  `terms.in.macro` 选项，如果改为 `#1` 时会将“et al.”改为`{\bibetal}`以宏的形式输出。这是因为在一些模板中需要在 LaTeX 端控制参考文献引用的语言，这样就可以在模板中修改 `\bibetal` 的内容。

我觉得可以改为 `citation.locale` 和 `bibliography.locale`，可选的值为 `en`、`zh`、`auto`（默认） 和 `macro`。

**Comment by GreenieQwQ** [comment]
感谢 @zepinglee 的解决方案！
